//@author kaikozlov
//@category Verification
// Validate synthetic RH850 fixture semantics against tests/fixtures/processor/manifest.json.
// Args: <absolute-manifest-json>
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.Instruction;
import ghidra.program.model.pcode.PcodeOp;
import ghidra.program.model.symbol.FlowType;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class AssertProcessorFixtureSemantics extends GhidraScript {
    // Minimal JSON subset parser to avoid depending on org.json in headless.
    // Manifest is generated by tools/build_processor_fixture.py.

    private final List<String> failures = new ArrayList<>();

    private void fail(String msg) {
        failures.add(msg);
        println("FAIL: " + msg);
    }

    private Set<String> pcodeOpNames(Instruction ins) {
        Set<String> ops = new HashSet<>();
        for (PcodeOp op : ins.getPcode()) {
            ops.add(op.getMnemonic());
        }
        return ops;
    }

    private boolean hasSignExtendFromLoad(Instruction ins, int loadSize) {
        PcodeOp[] ops = ins.getPcode();
        for (int i = 0; i < ops.length; i++) {
            if (ops[i].getOpcode() == PcodeOp.LOAD) {
                // Look ahead for INT_SEXT using the load output.
                for (int j = i + 1; j < Math.min(ops.length, i + 4); j++) {
                    if (ops[j].getOpcode() == PcodeOp.INT_SEXT) return true;
                }
            }
        }
        // Some SLEIGH emits sext(*) as a single LOAD into a truncated temp then SEXT.
        Set<String> names = pcodeOpNames(ins);
        return names.contains("INT_SEXT");
    }

    private boolean hasZeroExtendFromLoad(Instruction ins) {
        return pcodeOpNames(ins).contains("INT_ZEXT");
    }

    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        if (args.length != 1) {
            throw new IllegalArgumentException("expected absolute manifest.json path");
        }
        String text = Files.readString(Path.of(args[0]));
        // Very small hand-rolled extraction for cases array objects.
        List<Case> cases = Case.parseAll(text);
        println("AssertProcessorFixtureSemantics: cases=" + cases.size());

        for (Case c : cases) {
            Address addr = toAddr(c.addr);
            // Clear and disassemble exactly at the fixture address.
            Instruction existing = currentProgram.getListing().getInstructionContaining(addr);
            if (existing != null && !existing.getMinAddress().equals(addr)) {
                currentProgram.getListing().clearCodeUnits(
                    existing.getMinAddress(), existing.getMaxAddress(), false);
            }
            if (currentProgram.getListing().getInstructionAt(addr) == null) {
                disassemble(addr);
            }
            Instruction ins = currentProgram.getListing().getInstructionAt(addr);
            if (ins == null) {
                fail(c.name + ": failed to disassemble at 0x" + Long.toHexString(c.addr));
                continue;
            }
            String mnem = ins.getMnemonicString();
            if (c.mnemonicPrefix != null && (mnem == null || !mnem.startsWith(c.mnemonicPrefix))) {
                fail(c.name + ": mnemonic=" + mnem + " expected prefix " + c.mnemonicPrefix);
            }
            Set<String> ops = pcodeOpNames(ins);
            for (String need : c.mustPcodeOps) {
                if (!ops.contains(need)) {
                    fail(c.name + ": missing pcode op " + need + " in " + ops);
                }
            }
            for (String forbid : c.forbidPcodeOps) {
                if (ops.contains(forbid)) {
                    fail(c.name + ": forbidden pcode op " + forbid + " in " + ops);
                }
            }
            if (c.signExtend != null) {
                if (c.signExtend && !hasSignExtendFromLoad(ins, c.loadSize)) {
                    fail(c.name + ": expected INT_SEXT for signed load; ops=" + ops);
                }
                if (!c.signExtend && c.loadSize > 0 && !hasZeroExtendFromLoad(ins)
                        && !ops.contains("LOAD")) {
                    fail(c.name + ": expected zero-extending load; ops=" + ops);
                }
                if (!c.signExtend && hasSignExtendFromLoad(ins, c.loadSize)
                        && c.mnemonicPrefix != null && c.mnemonicPrefix.contains("u")) {
                    fail(c.name + ": unsigned load unexpectedly sign-extends; ops=" + ops);
                }
            }
            if (c.flow != null) {
                FlowType ft = ins.getFlowType();
                boolean ok = switch (c.flow) {
                    case "CALL" -> ft.isCall();
                    case "RETURN" -> ft.isTerminal() || "RETURN".equalsIgnoreCase(String.valueOf(ft));
                    case "BRANCH" -> ft.isJump();
                    default -> String.valueOf(ft).toUpperCase().contains(c.flow);
                };
                // Also accept CALL_RETURN etc.
                if (!ok) {
                    String s = String.valueOf(ft).toUpperCase();
                    if (c.flow.equals("RETURN") && (s.contains("RETURN") || s.contains("TERMINAL"))) ok = true;
                    if (c.flow.equals("CALL") && s.contains("CALL")) ok = true;
                }
                if (!ok) {
                    fail(c.name + ": flow=" + ft + " expected " + c.flow);
                }
            }
            println(String.format("  [%s] 0x%x %s ops=%s", c.name, c.addr, mnem, ops));
        }

        if (!failures.isEmpty()) {
            throw new IllegalStateException(failures.size() + " fixture failures: "
                    + String.join("; ", failures));
        }
        println("ASSERT processor-fixture: all " + cases.size() + " cases passed");
    }

    private static final class Case {
        String name;
        long addr;
        String mnemonicPrefix;
        List<String> mustPcodeOps = new ArrayList<>();
        List<String> forbidPcodeOps = new ArrayList<>();
        Integer loadSize;
        Boolean signExtend;
        String flow;

        static List<Case> parseAll(String text) {
            List<Case> out = new ArrayList<>();
            // Split on case objects inside the cases array by looking for "name":
            int casesIdx = text.indexOf("\"cases\"");
            if (casesIdx < 0) return out;
            int arr = text.indexOf('[', casesIdx);
            int end = text.lastIndexOf(']');
            String body = text.substring(arr + 1, end);
            String[] parts = body.split("\\},\\s*\\{");
            for (String part : parts) {
                String obj = part.trim();
                if (!obj.startsWith("{")) obj = "{" + obj;
                if (!obj.endsWith("}")) obj = obj + "}";
                Case c = new Case();
                c.name = extractString(obj, "name");
                c.addr = extractLong(obj, "addr");
                c.mnemonicPrefix = extractString(obj, "mnemonic_prefix");
                c.mustPcodeOps = extractStringArray(obj, "must_pcode_ops");
                c.forbidPcodeOps = extractStringArray(obj, "forbid_pcode_ops");
                if (obj.contains("\"load_size\"")) c.loadSize = (int) extractLong(obj, "load_size");
                if (obj.contains("\"sign_extend\"")) c.signExtend = extractBool(obj, "sign_extend");
                c.flow = extractString(obj, "flow");
                out.add(c);
            }
            return out;
        }

        private static String extractString(String obj, String key) {
            String needle = "\"" + key + "\"";
            int i = obj.indexOf(needle);
            if (i < 0) return null;
            int colon = obj.indexOf(':', i);
            int q1 = obj.indexOf('"', colon + 1);
            if (q1 < 0) return null;
            int q2 = obj.indexOf('"', q1 + 1);
            return obj.substring(q1 + 1, q2);
        }

        private static long extractLong(String obj, String key) {
            String needle = "\"" + key + "\"";
            int i = obj.indexOf(needle);
            if (i < 0) return -1;
            int colon = obj.indexOf(':', i);
            int j = colon + 1;
            while (j < obj.length() && Character.isWhitespace(obj.charAt(j))) j++;
            int k = j;
            while (k < obj.length() && (Character.isDigit(obj.charAt(k)) || obj.charAt(k) == '-')) k++;
            return Long.parseLong(obj.substring(j, k));
        }

        private static boolean extractBool(String obj, String key) {
            String needle = "\"" + key + "\"";
            int i = obj.indexOf(needle);
            int colon = obj.indexOf(':', i);
            int j = colon + 1;
            while (j < obj.length() && Character.isWhitespace(obj.charAt(j))) j++;
            return obj.startsWith("true", j);
        }

        private static List<String> extractStringArray(String obj, String key) {
            List<String> out = new ArrayList<>();
            String needle = "\"" + key + "\"";
            int i = obj.indexOf(needle);
            if (i < 0) return out;
            int lb = obj.indexOf('[', i);
            int rb = obj.indexOf(']', lb);
            if (lb < 0 || rb < 0) return out;
            String inner = obj.substring(lb + 1, rb).trim();
            if (inner.isEmpty()) return out;
            for (String piece : inner.split(",")) {
                String s = piece.trim();
                if (s.startsWith("\"") && s.endsWith("\"") && s.length() >= 2) {
                    out.add(s.substring(1, s.length() - 1));
                }
            }
            return out;
        }
    }
}
