//@author kaikozlov
//@category Verification
// Validate synthetic RH850 fixture semantics against tests/fixtures/processor/manifest.json.
// Args: <absolute-manifest-json>
import ghidra.app.script.GhidraScript;
import ghidra.app.emulator.EmulatorHelper;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.Instruction;
import ghidra.program.model.pcode.PcodeOp;
import ghidra.program.model.symbol.FlowType;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class AssertProcessorFixtureSemantics extends GhidraScript {
    // Minimal JSON subset parser to avoid depending on org.json in headless.
    // Manifest is generated by tools/build_processor_fixture.py.

    private final List<String> failures = new ArrayList<>();

    private void fail(String msg) {
        failures.add(msg);
        println("FAIL: " + msg);
    }

    private Set<String> pcodeOpNames(Instruction ins) {
        Set<String> ops = new HashSet<>();
        for (PcodeOp op : ins.getPcode()) {
            ops.add(op.getMnemonic());
        }
        return ops;
    }

    private boolean hasSignExtendFromLoad(Instruction ins, int loadSize) {
        PcodeOp[] ops = ins.getPcode();
        for (int i = 0; i < ops.length; i++) {
            if (ops[i].getOpcode() == PcodeOp.LOAD) {
                // Look ahead for INT_SEXT using the load output.
                for (int j = i + 1; j < Math.min(ops.length, i + 4); j++) {
                    if (ops[j].getOpcode() == PcodeOp.INT_SEXT) return true;
                }
            }
        }
        // Some SLEIGH emits sext(*) as a single LOAD into a truncated temp then SEXT.
        Set<String> names = pcodeOpNames(ins);
        return names.contains("INT_SEXT");
    }

    private boolean hasZeroExtendFromLoad(Instruction ins) {
        return pcodeOpNames(ins).contains("INT_ZEXT");
    }

    private EmulatorHelper emulator(long pc) {
        EmulatorHelper emu = new EmulatorHelper(currentProgram);
        emu.writeRegister("PC", pc);
        return emu;
    }

    private void step(EmulatorHelper emu, String label) throws Exception {
        if (!emu.step(monitor)) {
            fail(label + ": emulator step failed: " + emu.getLastError());
        }
    }

    private void requireRegister(EmulatorHelper emu, String label,
                                 String register, long expected) {
        long actual = emu.readRegister(register).longValue() & 0xffffffffL;
        if (actual != (expected & 0xffffffffL)) {
            fail(String.format("%s: %s=0x%x expected=0x%x",
                    label, register, actual, expected & 0xffffffffL));
        }
    }

    private long requireCaseAddr(java.util.Map<String, Long> addrs, String name) {
        Long addr = addrs.get(name);
        if (addr == null) {
            fail("execution vector missing fixture case: " + name);
            return -1;
        }
        return addr;
    }

    private boolean pswBit(EmulatorHelper emu, int bit) {
        return (emu.readRegister("PSW").longValue() & (1L << bit)) != 0;
    }

    private void runExecutionVectors(java.util.Map<String, Long> addrs) throws Exception {
        long a;

        a = requireCaseAddr(addrs, "sld.b");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("ep", 0x1000);
                emu.writeMemory(toAddr(0x1010), new byte[]{(byte) 0x80});
                step(emu, "sld.b negative");
                requireRegister(emu, "sld.b negative", "r10", 0xffffff80L);
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "sld.h");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("ep", 0x1000);
                emu.writeMemory(toAddr(0x1020), new byte[]{0x01, (byte) 0x80});
                step(emu, "sld.h negative");
                requireRegister(emu, "sld.h negative", "r11", 0xffff8001L);
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "ld.w");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("gp", 0x1000); // ld.w disp[r4/gp], r10
                emu.writeMemory(toAddr(0x10b0),
                        new byte[]{0x78, 0x56, 0x34, 0x12});
                step(emu, "ld.w scaled displacement");
                requireRegister(emu, "ld.w scaled displacement", "r10", 0x12345678L);
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "divh");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0xfffffffeL);
                emu.writeRegister("r10", 7);
                emu.writeRegister("PSW", 0);
                step(emu, "divh signed");
                requireRegister(emu, "divh signed", "r10", 0xfffffffdL);
            } finally {
                emu.dispose();
            }

            emu = emulator(a);
            try {
                emu.writeRegister("r6", 0);
                emu.writeRegister("r10", 0x12345678L);
                emu.writeRegister("PSW", 0);
                step(emu, "divh divide by zero");
                requireRegister(emu, "divh divide by zero", "r10", 0x12345678L);
                if (!pswBit(emu, 2)) {
                    fail(String.format("divh divide by zero: PSW=0x%x lacks OV",
                            emu.readRegister("PSW").longValue()));
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "satadd");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 1);
                emu.writeRegister("r10", 0x7fffffffL);
                emu.writeRegister("PSW", 0);
                step(emu, "satadd positive overflow");
                requireRegister(emu, "satadd positive overflow", "r10", 0x7fffffffL);
                if (!pswBit(emu, 4) || !pswBit(emu, 2)) {
                    fail(String.format("satadd positive overflow: PSW=0x%x lacks SAT/OV",
                            emu.readRegister("PSW").longValue()));
                }
            } finally {
                emu.dispose();
            }

            emu = emulator(a);
            try {
                emu.writeRegister("r6", 0xffffffffL);
                emu.writeRegister("r10", 1);
                emu.writeRegister("PSW", 0);
                step(emu, "satadd carry without overflow");
                requireRegister(emu, "satadd carry without overflow", "r10", 0);
                if (pswBit(emu, 4) || pswBit(emu, 2) || !pswBit(emu, 3)) {
                    fail(String.format(
                            "satadd carry without overflow: PSW=0x%x expected CY only",
                            emu.readRegister("PSW").longValue()));
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "prepare");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("sp", 0x2800);
                emu.writeRegister("lp", 0x12345678L);
                step(emu, "prepare stack effect");
                requireRegister(emu, "prepare stack effect", "sp", 0x27f4);
                long saved = ((long) emu.readMemoryByte(toAddr(0x27fc)) & 0xff)
                        | (((long) emu.readMemoryByte(toAddr(0x27fd)) & 0xff) << 8)
                        | (((long) emu.readMemoryByte(toAddr(0x27fe)) & 0xff) << 16)
                        | (((long) emu.readMemoryByte(toAddr(0x27ff)) & 0xff) << 24);
                if (saved != 0x12345678L) {
                    fail(String.format("prepare saved lp=0x%x expected=0x12345678", saved));
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "dispose");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("sp", 0x27f4);
                emu.writeMemory(toAddr(0x27fc),
                        new byte[]{0x78, 0x56, 0x34, 0x12});
                step(emu, "dispose stack effect");
                requireRegister(emu, "dispose stack effect", "sp", 0x2800);
                requireRegister(emu, "dispose stack effect", "lp", 0x12345678L);
            } finally {
                emu.dispose();
            }
        }

        // switch r6 with table[0]=+2 → PC = inst_next + 4
        a = requireCaseAddr(addrs, "switch");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0);
                step(emu, "switch case0");
                requireRegister(emu, "switch case0", "PC", a + 2 + 4);
            } finally {
                emu.dispose();
            }
        }

        // callt idx=4: CTBP table entry supplies byte offset to target.
        a = requireCaseAddr(addrs, "callt");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                long ctbp = 0x2000;
                emu.writeRegister("CTBP", ctbp);
                emu.writeRegister("PSW", 0x11);
                // lbl = CTBP + (4<<1) = CTBP+8; halfword there is byte offset 0x20.
                emu.writeMemory(toAddr(ctbp + 8), new byte[]{0x20, 0x00});
                step(emu, "callt table lookup");
                requireRegister(emu, "callt table lookup", "PC", ctbp + 0x20);
                requireRegister(emu, "callt table lookup", "CTPC", a + 2);
                requireRegister(emu, "callt table lookup", "CTPSW", 0x11);
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "bins");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0xf);
                emu.writeRegister("r10", 0xffff0000L);
                emu.writeRegister("PSW", 0);
                step(emu, "bins insert nibble");
                requireRegister(emu, "bins insert nibble", "r10", 0xffff00f0L);
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "set1");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0x3000);
                emu.writeRegister("PSW", 0);
                emu.writeMemory(toAddr(0x3000), new byte[]{0x00});
                step(emu, "set1 bit3");
                byte got = emu.readMemoryByte(toAddr(0x3000));
                if (got != 0x08) {
                    fail(String.format("set1 bit3: mem=0x%x expected=0x08", got & 0xff));
                }
                if (!pswBit(emu, 0)) {
                    fail("set1 bit3: expected Z set when prior bit was clear");
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "clr1");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0x3000);
                emu.writeRegister("PSW", 0);
                emu.writeMemory(toAddr(0x3000), new byte[]{0x0f});
                step(emu, "clr1 bit3");
                byte got = emu.readMemoryByte(toAddr(0x3000));
                if (got != 0x07) {
                    fail(String.format("clr1 bit3: mem=0x%x expected=0x07", got & 0xff));
                }
                if (pswBit(emu, 0)) {
                    fail("clr1 bit3: expected Z clear when prior bit was set");
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "tst1");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0x3000);
                emu.writeRegister("PSW", 0);
                emu.writeMemory(toAddr(0x3000), new byte[]{0x08});
                step(emu, "tst1 bit3 set");
                byte got = emu.readMemoryByte(toAddr(0x3000));
                if (got != 0x08) {
                    fail(String.format("tst1 bit3: mem mutated to 0x%x", got & 0xff));
                }
                if (pswBit(emu, 0)) {
                    fail("tst1 bit3 set: expected Z clear");
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "cmovne");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0x11111111L);
                emu.writeRegister("r10", 0x22222222L);
                emu.writeRegister("r11", 0);
                emu.writeRegister("PSW", 0); // Z clear → ne taken
                step(emu, "cmovne taken");
                requireRegister(emu, "cmovne taken", "r11", 0x11111111L);
            } finally {
                emu.dispose();
            }

            emu = emulator(a);
            try {
                emu.writeRegister("r6", 0x11111111L);
                emu.writeRegister("r10", 0x22222222L);
                emu.writeRegister("r11", 0);
                emu.writeRegister("PSW", 1); // Z set → ne not taken
                step(emu, "cmovne not taken");
                requireRegister(emu, "cmovne not taken", "r11", 0x22222222L);
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "mulhi");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0xfffffffeL); // low16 = -2
                emu.writeRegister("r10", 0);
                step(emu, "mulhi signed halfword");
                requireRegister(emu, "mulhi signed halfword", "r10", 0xffffffe0L); // -2 * 16
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "sar");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r10", 0xfffffff0L);
                emu.writeRegister("PSW", 0);
                step(emu, "sar sign extend");
                requireRegister(emu, "sar sign extend", "r10", 0xffffffffL);
            } finally {
                emu.dispose();
            }
        }
    }

    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        if (args.length != 1) {
            throw new IllegalArgumentException("expected absolute manifest.json path");
        }
        String text = Files.readString(Path.of(args[0]));
        // Very small hand-rolled extraction for cases array objects.
        List<Case> cases = Case.parseAll(text);
        println("AssertProcessorFixtureSemantics: cases=" + cases.size());
        java.util.Map<String, Long> addrs = new java.util.HashMap<>();
        for (Case c : cases) {
            addrs.put(c.name, c.addr);
        }

        for (Case c : cases) {
            Address addr = toAddr(c.addr);
            // Clear and disassemble exactly at the fixture address.
            Instruction existing = currentProgram.getListing().getInstructionContaining(addr);
            if (existing != null && !existing.getMinAddress().equals(addr)) {
                currentProgram.getListing().clearCodeUnits(
                    existing.getMinAddress(), existing.getMaxAddress(), false);
            }
            if (currentProgram.getListing().getInstructionAt(addr) == null) {
                disassemble(addr);
            }
            Instruction ins = currentProgram.getListing().getInstructionAt(addr);
            if (ins == null) {
                fail(c.name + ": failed to disassemble at 0x" + Long.toHexString(c.addr));
                continue;
            }
            String mnem = ins.getMnemonicString();
            if (c.mnemonicPrefix != null && (mnem == null || !mnem.startsWith(c.mnemonicPrefix))) {
                fail(c.name + ": mnemonic=" + mnem + " expected prefix " + c.mnemonicPrefix);
            }
            Set<String> ops = pcodeOpNames(ins);
            for (String need : c.mustPcodeOps) {
                if (!ops.contains(need)) {
                    fail(c.name + ": missing pcode op " + need + " in " + ops);
                }
            }
            for (String forbid : c.forbidPcodeOps) {
                if (ops.contains(forbid)) {
                    fail(c.name + ": forbidden pcode op " + forbid + " in " + ops);
                }
            }
            if (c.signExtend != null) {
                if (c.signExtend && !hasSignExtendFromLoad(ins, c.loadSize)) {
                    fail(c.name + ": expected INT_SEXT for signed load; ops=" + ops);
                }
                if (!c.signExtend && c.loadSize > 0 && !hasZeroExtendFromLoad(ins)
                        && !ops.contains("LOAD")) {
                    fail(c.name + ": expected zero-extending load; ops=" + ops);
                }
                if (!c.signExtend && hasSignExtendFromLoad(ins, c.loadSize)
                        && c.mnemonicPrefix != null && c.mnemonicPrefix.contains("u")) {
                    fail(c.name + ": unsigned load unexpectedly sign-extends; ops=" + ops);
                }
            }
            if (c.flow != null) {
                FlowType ft = ins.getFlowType();
                boolean ok = switch (c.flow) {
                    case "CALL" -> ft.isCall();
                    case "RETURN" -> ft.isTerminal() || "RETURN".equalsIgnoreCase(String.valueOf(ft));
                    case "BRANCH" -> ft.isJump();
                    default -> String.valueOf(ft).toUpperCase().contains(c.flow);
                };
                // Also accept CALL_RETURN etc.
                if (!ok) {
                    String s = String.valueOf(ft).toUpperCase();
                    if (c.flow.equals("RETURN") && (s.contains("RETURN") || s.contains("TERMINAL"))) ok = true;
                    if (c.flow.equals("CALL") && s.contains("CALL")) ok = true;
                }
                if (!ok) {
                    fail(c.name + ": flow=" + ft + " expected " + c.flow);
                }
            }
            println(String.format("  [%s] 0x%x %s ops=%s", c.name, c.addr, mnem, ops));
        }

        runExecutionVectors(addrs);

        if (!failures.isEmpty()) {
            throw new IllegalStateException(failures.size() + " fixture failures: "
                    + String.join("; ", failures));
        }
        println("ASSERT processor-fixture: all " + cases.size() + " cases passed");
    }

    private static final class Case {
        String name;
        long addr;
        String mnemonicPrefix;
        List<String> mustPcodeOps = new ArrayList<>();
        List<String> forbidPcodeOps = new ArrayList<>();
        Integer loadSize;
        Boolean signExtend;
        String flow;

        static List<Case> parseAll(String text) {
            List<Case> out = new ArrayList<>();
            // Split on case objects inside the cases array by looking for "name":
            int casesIdx = text.indexOf("\"cases\"");
            if (casesIdx < 0) return out;
            int arr = text.indexOf('[', casesIdx);
            int end = text.lastIndexOf(']');
            String body = text.substring(arr + 1, end);
            String[] parts = body.split("\\},\\s*\\{");
            for (String part : parts) {
                String obj = part.trim();
                if (!obj.startsWith("{")) obj = "{" + obj;
                if (!obj.endsWith("}")) obj = obj + "}";
                Case c = new Case();
                c.name = extractString(obj, "name");
                c.addr = extractLong(obj, "addr");
                c.mnemonicPrefix = extractString(obj, "mnemonic_prefix");
                c.mustPcodeOps = extractStringArray(obj, "must_pcode_ops");
                c.forbidPcodeOps = extractStringArray(obj, "forbid_pcode_ops");
                if (obj.contains("\"load_size\"")) c.loadSize = (int) extractLong(obj, "load_size");
                if (obj.contains("\"sign_extend\"")) c.signExtend = extractBool(obj, "sign_extend");
                c.flow = extractString(obj, "flow");
                out.add(c);
            }
            return out;
        }

        private static String extractString(String obj, String key) {
            String needle = "\"" + key + "\"";
            int i = obj.indexOf(needle);
            if (i < 0) return null;
            int colon = obj.indexOf(':', i);
            int q1 = obj.indexOf('"', colon + 1);
            if (q1 < 0) return null;
            int q2 = obj.indexOf('"', q1 + 1);
            return obj.substring(q1 + 1, q2);
        }

        private static long extractLong(String obj, String key) {
            String needle = "\"" + key + "\"";
            int i = obj.indexOf(needle);
            if (i < 0) return -1;
            int colon = obj.indexOf(':', i);
            int j = colon + 1;
            while (j < obj.length() && Character.isWhitespace(obj.charAt(j))) j++;
            int k = j;
            while (k < obj.length() && (Character.isDigit(obj.charAt(k)) || obj.charAt(k) == '-')) k++;
            return Long.parseLong(obj.substring(j, k));
        }

        private static boolean extractBool(String obj, String key) {
            String needle = "\"" + key + "\"";
            int i = obj.indexOf(needle);
            int colon = obj.indexOf(':', i);
            int j = colon + 1;
            while (j < obj.length() && Character.isWhitespace(obj.charAt(j))) j++;
            return obj.startsWith("true", j);
        }

        private static List<String> extractStringArray(String obj, String key) {
            List<String> out = new ArrayList<>();
            String needle = "\"" + key + "\"";
            int i = obj.indexOf(needle);
            if (i < 0) return out;
            int lb = obj.indexOf('[', i);
            int rb = obj.indexOf(']', lb);
            if (lb < 0 || rb < 0) return out;
            String inner = obj.substring(lb + 1, rb).trim();
            if (inner.isEmpty()) return out;
            for (String piece : inner.split(",")) {
                String s = piece.trim();
                if (s.startsWith("\"") && s.endsWith("\"") && s.length() >= 2) {
                    out.add(s.substring(1, s.length() - 1));
                }
            }
            return out;
        }
    }
}
