//@author kaikozlov
//@category Verification
// Validate synthetic RH850 fixture semantics against tests/fixtures/processor/manifest.json.
// Args: <absolute-manifest-json>
import ghidra.app.script.GhidraScript;
import ghidra.app.emulator.EmulatorHelper;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.Instruction;
import ghidra.program.model.pcode.PcodeOp;
import ghidra.program.model.symbol.FlowType;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class AssertProcessorFixtureSemantics extends GhidraScript {
    // Minimal JSON subset parser to avoid depending on org.json in headless.
    // Manifest is generated by tools/testing/processor/build_processor_fixture.py.

    private final List<String> failures = new ArrayList<>();

    private void fail(String msg) {
        failures.add(msg);
        println("FAIL: " + msg);
    }

    private Set<String> pcodeOpNames(Instruction ins) {
        Set<String> ops = new HashSet<>();
        for (PcodeOp op : ins.getPcode()) {
            ops.add(op.getMnemonic());
        }
        return ops;
    }

    private String useropName(Instruction ins) {
        for (PcodeOp op : ins.getPcode()) {
            if (op.getOpcode() != PcodeOp.CALLOTHER) continue;
            int index = (int) op.getInput(0).getOffset();
            return currentProgram.getLanguage().getUserDefinedOpName(index);
        }
        return null;
    }

    private boolean hasSignExtendFromLoad(Instruction ins, int loadSize) {
        PcodeOp[] ops = ins.getPcode();
        for (int i = 0; i < ops.length; i++) {
            if (ops[i].getOpcode() == PcodeOp.LOAD) {
                // Look ahead for INT_SEXT using the load output.
                for (int j = i + 1; j < Math.min(ops.length, i + 4); j++) {
                    if (ops[j].getOpcode() == PcodeOp.INT_SEXT) return true;
                }
            }
        }
        // Some SLEIGH emits sext(*) as a single LOAD into a truncated temp then SEXT.
        Set<String> names = pcodeOpNames(ins);
        return names.contains("INT_SEXT");
    }

    private boolean hasZeroExtendFromLoad(Instruction ins) {
        return pcodeOpNames(ins).contains("INT_ZEXT");
    }

    private EmulatorHelper emulator(long pc) {
        EmulatorHelper emu = new EmulatorHelper(currentProgram);
        emu.writeRegister("PC", pc);
        return emu;
    }

    private void step(EmulatorHelper emu, String label) throws Exception {
        if (!emu.step(monitor)) {
            fail(label + ": emulator step failed: " + emu.getLastError());
        }
    }

    private void stepInterruptControl(EmulatorHelper emu, String label,
                                      String expectedUserop) throws Exception {
        if (emu.step(monitor)) return;
        String error = emu.getLastError();
        if (error == null || !error.contains(expectedUserop)) {
            fail(label + ": unexpected emulator failure: " + error);
        }
    }

    private void requireRegister(EmulatorHelper emu, String label,
                                 String register, long expected) {
        long actual = emu.readRegister(register).longValue() & 0xffffffffL;
        if (actual != (expected & 0xffffffffL)) {
            fail(String.format("%s: %s=0x%x expected=0x%x",
                    label, register, actual, expected & 0xffffffffL));
        }
    }

    private long readU32(EmulatorHelper emu, long address) {
        return ((long) emu.readMemoryByte(toAddr(address)) & 0xff)
                | (((long) emu.readMemoryByte(toAddr(address + 1)) & 0xff) << 8)
                | (((long) emu.readMemoryByte(toAddr(address + 2)) & 0xff) << 16)
                | (((long) emu.readMemoryByte(toAddr(address + 3)) & 0xff) << 24);
    }

    private long requireCaseAddr(java.util.Map<String, Long> addrs, String name) {
        Long addr = addrs.get(name);
        if (addr == null) {
            fail("execution vector missing fixture case: " + name);
            return -1;
        }
        return addr;
    }

    private boolean pswBit(EmulatorHelper emu, int bit) {
        return (emu.readRegister("PSW").longValue() & (1L << bit)) != 0;
    }

    private void verifyLdsr(java.util.Map<String, Long> addrs, String name,
                            String systemRegister, long value) throws Exception {
        long address = requireCaseAddr(addrs, name);
        if (address < 0) return;
        EmulatorHelper emu = emulator(address);
        try {
            emu.writeRegister("r6", value);
            step(emu, name);
            requireRegister(emu, name, systemRegister, value);
        } finally {
            emu.dispose();
        }
    }

    private void verifyStsr(java.util.Map<String, Long> addrs, String name,
                            String systemRegister, long value) throws Exception {
        long address = requireCaseAddr(addrs, name);
        if (address < 0) return;
        EmulatorHelper emu = emulator(address);
        try {
            emu.writeRegister(systemRegister, value);
            step(emu, name);
            requireRegister(emu, name, "r10", value);
        } finally {
            emu.dispose();
        }
    }

    private void runExecutionVectors(java.util.Map<String, Long> addrs) throws Exception {
        long a;

        a = requireCaseAddr(addrs, "sld.b");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("ep", 0x1000);
                emu.writeMemory(toAddr(0x1010), new byte[]{(byte) 0x80});
                step(emu, "sld.b negative");
                requireRegister(emu, "sld.b negative", "r10", 0xffffff80L);
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "sld.h");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("ep", 0x1000);
                emu.writeMemory(toAddr(0x1020), new byte[]{0x01, (byte) 0x80});
                step(emu, "sld.h negative");
                requireRegister(emu, "sld.h negative", "r11", 0xffff8001L);
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "ld.w");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("gp", 0x1000); // ld.w disp[r4/gp], r10
                emu.writeMemory(toAddr(0x10b0),
                        new byte[]{0x78, 0x56, 0x34, 0x12});
                step(emu, "ld.w scaled displacement");
                requireRegister(emu, "ld.w scaled displacement", "r10", 0x12345678L);
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "divh");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0xfffffffeL);
                emu.writeRegister("r10", 7);
                emu.writeRegister("PSW", 0);
                step(emu, "divh signed");
                requireRegister(emu, "divh signed", "r10", 0xfffffffdL);
            } finally {
                emu.dispose();
            }

            emu = emulator(a);
            try {
                emu.writeRegister("r6", 0);
                emu.writeRegister("r10", 0x12345678L);
                emu.writeRegister("PSW", 0);
                step(emu, "divh divide by zero");
                requireRegister(emu, "divh divide by zero", "r10", 0x12345678L);
                if (!pswBit(emu, 2)) {
                    fail(String.format("divh divide by zero: PSW=0x%x lacks OV",
                            emu.readRegister("PSW").longValue()));
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "satadd");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 1);
                emu.writeRegister("r10", 0x7fffffffL);
                emu.writeRegister("PSW", 0);
                step(emu, "satadd positive overflow");
                requireRegister(emu, "satadd positive overflow", "r10", 0x7fffffffL);
                if (!pswBit(emu, 4) || !pswBit(emu, 2)) {
                    fail(String.format("satadd positive overflow: PSW=0x%x lacks SAT/OV",
                            emu.readRegister("PSW").longValue()));
                }
            } finally {
                emu.dispose();
            }

            emu = emulator(a);
            try {
                emu.writeRegister("r6", 0xffffffffL);
                emu.writeRegister("r10", 1);
                emu.writeRegister("PSW", 0);
                step(emu, "satadd carry without overflow");
                requireRegister(emu, "satadd carry without overflow", "r10", 0);
                if (pswBit(emu, 4) || pswBit(emu, 2) || !pswBit(emu, 3)) {
                    fail(String.format(
                            "satadd carry without overflow: PSW=0x%x expected CY only",
                            emu.readRegister("PSW").longValue()));
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "prepare");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("sp", 0x2800);
                emu.writeRegister("lp", 0x12345678L);
                step(emu, "prepare stack effect");
                requireRegister(emu, "prepare stack effect", "sp", 0x27f4);
                long saved = ((long) emu.readMemoryByte(toAddr(0x27fc)) & 0xff)
                        | (((long) emu.readMemoryByte(toAddr(0x27fd)) & 0xff) << 8)
                        | (((long) emu.readMemoryByte(toAddr(0x27fe)) & 0xff) << 16)
                        | (((long) emu.readMemoryByte(toAddr(0x27ff)) & 0xff) << 24);
                if (saved != 0x12345678L) {
                    fail(String.format("prepare saved lp=0x%x expected=0x12345678", saved));
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "dispose");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("sp", 0x27f4);
                emu.writeMemory(toAddr(0x27fc),
                        new byte[]{0x78, 0x56, 0x34, 0x12});
                step(emu, "dispose stack effect");
                requireRegister(emu, "dispose stack effect", "sp", 0x2800);
                requireRegister(emu, "dispose stack effect", "lp", 0x12345678L);
            } finally {
                emu.dispose();
            }
        }

        // switch r6 with table[0]=+2 → PC = inst_next + 4
        a = requireCaseAddr(addrs, "switch");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0);
                step(emu, "switch case0");
                requireRegister(emu, "switch case0", "PC", a + 2 + 4);
            } finally {
                emu.dispose();
            }
        }

        // callt idx=4: CTBP table entry supplies byte offset to target.
        a = requireCaseAddr(addrs, "callt");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                long ctbp = 0x2000;
                emu.writeRegister("CTBP", ctbp);
                emu.writeRegister("PSW", 0x40008011L);
                // lbl = CTBP + (4<<1) = CTBP+8; halfword there is byte offset 0x20.
                emu.writeMemory(toAddr(ctbp + 8), new byte[]{0x20, 0x00});
                step(emu, "callt table lookup");
                requireRegister(emu, "callt table lookup", "PC", ctbp + 0x20);
                requireRegister(emu, "callt table lookup", "CTPC", a + 2);
                requireRegister(emu, "callt table lookup", "CTPSW", 0x11);
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "bins");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0xf);
                emu.writeRegister("r10", 0xffff0000L);
                emu.writeRegister("PSW", 0);
                step(emu, "bins insert nibble");
                requireRegister(emu, "bins insert nibble", "r10", 0xffff00f0L);
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "set1");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0x3000);
                emu.writeRegister("PSW", 0);
                emu.writeMemory(toAddr(0x3000), new byte[]{0x00});
                step(emu, "set1 bit3");
                byte got = emu.readMemoryByte(toAddr(0x3000));
                if (got != 0x08) {
                    fail(String.format("set1 bit3: mem=0x%x expected=0x08", got & 0xff));
                }
                if (!pswBit(emu, 0)) {
                    fail("set1 bit3: expected Z set when prior bit was clear");
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "clr1");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0x3000);
                emu.writeRegister("PSW", 0);
                emu.writeMemory(toAddr(0x3000), new byte[]{0x0f});
                step(emu, "clr1 bit3");
                byte got = emu.readMemoryByte(toAddr(0x3000));
                if (got != 0x07) {
                    fail(String.format("clr1 bit3: mem=0x%x expected=0x07", got & 0xff));
                }
                if (pswBit(emu, 0)) {
                    fail("clr1 bit3: expected Z clear when prior bit was set");
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "tst1");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0x3000);
                emu.writeRegister("PSW", 0);
                emu.writeMemory(toAddr(0x3000), new byte[]{0x08});
                step(emu, "tst1 bit3 set");
                byte got = emu.readMemoryByte(toAddr(0x3000));
                if (got != 0x08) {
                    fail(String.format("tst1 bit3: mem mutated to 0x%x", got & 0xff));
                }
                if (pswBit(emu, 0)) {
                    fail("tst1 bit3 set: expected Z clear");
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "cmovne");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0x11111111L);
                emu.writeRegister("r10", 0x22222222L);
                emu.writeRegister("r11", 0);
                emu.writeRegister("PSW", 0); // Z clear → ne taken
                step(emu, "cmovne taken");
                requireRegister(emu, "cmovne taken", "r11", 0x11111111L);
            } finally {
                emu.dispose();
            }

            emu = emulator(a);
            try {
                emu.writeRegister("r6", 0x11111111L);
                emu.writeRegister("r10", 0x22222222L);
                emu.writeRegister("r11", 0);
                emu.writeRegister("PSW", 1); // Z set → ne not taken
                step(emu, "cmovne not taken");
                requireRegister(emu, "cmovne not taken", "r11", 0x22222222L);
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "mulhi");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0xfffffffeL); // low16 = -2
                emu.writeRegister("r10", 0);
                step(emu, "mulhi signed halfword");
                requireRegister(emu, "mulhi signed halfword", "r10", 0xffffffe0L); // -2 * 16
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "sar");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r10", 0xfffffff0L);
                emu.writeRegister("PSW", 0);
                step(emu, "sar sign extend");
                requireRegister(emu, "sar sign extend", "r10", 0xffffffffL);
            } finally {
                emu.dispose();
            }
        }
        a = requireCaseAddr(addrs, "jarl_indirect_alias");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0x12345678L);
                step(emu, "jarl indirect alias");
                requireRegister(emu, "jarl indirect alias", "PC", 0x12345678L);
                requireRegister(emu, "jarl indirect alias", "r6", a + 4);
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "divq");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0xfffffffeL);
                emu.writeRegister("r10", 7);
                step(emu, "divq signed");
                requireRegister(emu, "divq signed", "r10", 0xfffffffdL);
                requireRegister(emu, "divq signed", "r11", 1);
            } finally {
                emu.dispose();
            }

            emu = emulator(a);
            try {
                emu.writeRegister("r6", 0);
                emu.writeRegister("r10", 0x12345678L);
                emu.writeRegister("r11", 0xabcdef01L);
                step(emu, "divq zero");
                requireRegister(emu, "divq zero", "r10", 0x12345678L);
                requireRegister(emu, "divq zero", "r11", 0xabcdef01L);
                if (!pswBit(emu, 2)) fail("divq zero did not set PSW.OV");
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "divqu");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 3);
                emu.writeRegister("r10", 0xfffffffeL);
                step(emu, "divqu unsigned");
                requireRegister(emu, "divqu unsigned", "r10", 0x55555554L);
                requireRegister(emu, "divqu unsigned", "r11", 2);
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "loop");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 1);
                emu.writeRegister("PSW", 0);
                step(emu, "loop terminal");
                requireRegister(emu, "loop terminal", "r6", 0);
                requireRegister(emu, "loop terminal", "PC", a + 4);
                if (!pswBit(emu, 0) || !pswBit(emu, 3)) {
                    fail("loop terminal did not update Z/CY");
                }
            } finally {
                emu.dispose();
            }

            emu = emulator(a);
            try {
                emu.writeRegister("r6", 2);
                step(emu, "loop taken");
                requireRegister(emu, "loop taken", "r6", 1);
                requireRegister(emu, "loop taken", "PC", a - 4);
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "shl-reg");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 36); // architectural shift count is low 5 bits
                emu.writeRegister("r10", 0x10000001L);
                emu.writeRegister("PSW", 0);
                step(emu, "shl register count");
                requireRegister(emu, "shl register count", "r11", 0x10);
                if (!pswBit(emu, 3)) fail("shl register count did not set carry");
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "rotl-zero");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r10", 0x80000001L);
                emu.writeRegister("PSW", 0);
                step(emu, "rotl zero");
                requireRegister(emu, "rotl zero", "r11", 0x80000001L);
                if (!pswBit(emu, 3)) fail("rotl zero did not copy result bit 0 to CY");
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "sch0r");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r10", 0xfffffffeL);
                emu.writeRegister("PSW", 0x6);
                step(emu, "sch0r first bit");
                requireRegister(emu, "sch0r first bit", "r11", 1);
                if (!pswBit(emu, 3) || pswBit(emu, 2) || pswBit(emu, 1)) {
                    fail("sch0r flags do not match found-first-bit result");
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "sch1l");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r10", 0x80000000L);
                step(emu, "sch1l first bit");
                requireRegister(emu, "sch1l first bit", "r11", 1);
            } finally {
                emu.dispose();
            }

            emu = emulator(a);
            try {
                emu.writeRegister("r10", 0);
                step(emu, "sch1l not found");
                requireRegister(emu, "sch1l not found", "r11", 0);
                if (!pswBit(emu, 0) || pswBit(emu, 3)) {
                    fail("sch1l not-found flags are incorrect");
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "bsh");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r10", 0x12340000L);
                emu.writeRegister("PSW", 0);
                step(emu, "bsh lower-half flags");
                requireRegister(emu, "bsh lower-half flags", "r11", 0x34120000L);
                if (!pswBit(emu, 0) || !pswBit(emu, 3)) {
                    fail("bsh did not derive Z/CY from the lower halfword");
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "hsh");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r10", 0x80010000L);
                emu.writeRegister("PSW", 0);
                step(emu, "hsh lower-half flags");
                requireRegister(emu, "hsh lower-half flags", "r11", 0x80010000L);
                if (!pswBit(emu, 0) || !pswBit(emu, 3) || !pswBit(emu, 1)) {
                    fail("hsh did not derive Z/CY from lower halfword and S from word");
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "set1-reg");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0x3000);
                emu.writeRegister("r10", 11); // low 3 bits select bit 3
                emu.writeMemory(toAddr(0x3000), new byte[]{0});
                step(emu, "set1 register bit index");
                if ((emu.readMemoryByte(toAddr(0x3000)) & 0xff) != 0x08) {
                    fail("set1 register bit index did not mask to three bits");
                }
            } finally {
                emu.dispose();
            }
        }

        long ldlAddr = requireCaseAddr(addrs, "ldl.w");
        long stcAddr = requireCaseAddr(addrs, "stc.w");
        long cllAddr = requireCaseAddr(addrs, "cll");
        if (ldlAddr >= 0 && stcAddr >= 0 && cllAddr >= 0) {
            EmulatorHelper emu = emulator(ldlAddr);
            try {
                emu.writeRegister("r6", 0x3000);
                emu.writeMemory(toAddr(0x3000),
                        new byte[]{0x44, 0x33, 0x22, 0x11});
                step(emu, "ldl.w link");
                requireRegister(emu, "ldl.w link", "r11", 0x11223344L);
                emu.writeRegister("r11", 0x55667788L);
                emu.writeRegister("PC", stcAddr);
                step(emu, "stc.w linked success");
                requireRegister(emu, "stc.w linked success", "r11", 1);
                if (readU32(emu, 0x3000) != 0x55667788L) {
                    fail("stc.w linked success did not store");
                }
            } finally {
                emu.dispose();
            }

            emu = emulator(ldlAddr);
            try {
                emu.writeRegister("r6", 0x3000);
                emu.writeMemory(toAddr(0x3000),
                        new byte[]{0x44, 0x33, 0x22, 0x11});
                step(emu, "ldl.w before cll");
                emu.writeRegister("PC", cllAddr);
                step(emu, "cll clears link");
                emu.writeRegister("r11", 0x55667788L);
                emu.writeRegister("PC", stcAddr);
                step(emu, "stc.w after cll");
                requireRegister(emu, "stc.w after cll", "r11", 0);
                if (readU32(emu, 0x3000) != 0x11223344L) {
                    fail("stc.w after cll unexpectedly stored");
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "cmovf.s");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0x11111111L);
                emu.writeRegister("r10", 0x22222222L);
                emu.writeRegister("FPSR", 1L << 26);
                step(emu, "cmovf.s true");
                requireRegister(emu, "cmovf.s true", "r11", 0x11111111L);
            } finally {
                emu.dispose();
            }

            emu = emulator(a);
            try {
                emu.writeRegister("r6", 0x11111111L);
                emu.writeRegister("r10", 0x22222222L);
                emu.writeRegister("FPSR", 0);
                step(emu, "cmovf.s false");
                requireRegister(emu, "cmovf.s false", "r11", 0x22222222L);
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "caxi");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("r6", 0x3000);
                emu.writeRegister("r10", 0x11223344L);
                emu.writeRegister("r11", 0x55667788L);
                emu.writeRegister("PSW", 0);
                emu.writeMemory(toAddr(0x3000),
                        new byte[]{0x44, 0x33, 0x22, 0x11});
                step(emu, "caxi compare-match");
                requireRegister(emu, "caxi compare-match", "r11", 0x11223344L);
                requireRegister(emu, "caxi compare-match memory", "r6", 0x3000);
                long stored = ((long) emu.readMemoryByte(toAddr(0x3000)) & 0xff)
                        | (((long) emu.readMemoryByte(toAddr(0x3001)) & 0xff) << 8)
                        | (((long) emu.readMemoryByte(toAddr(0x3002)) & 0xff) << 16)
                        | (((long) emu.readMemoryByte(toAddr(0x3003)) & 0xff) << 24);
                if (stored != 0x55667788L || !pswBit(emu, 0)) {
                    fail(String.format("caxi compare-match: mem=0x%x PSW=0x%x",
                            stored, emu.readRegister("PSW").longValue()));
                }
            } finally {
                emu.dispose();
            }

            emu = emulator(a);
            try {
                emu.writeRegister("r6", 0x3000);
                emu.writeRegister("r10", 0x01020304L);
                emu.writeRegister("r11", 0x55667788L);
                emu.writeRegister("PSW", 0);
                emu.writeMemory(toAddr(0x3000),
                        new byte[]{0x44, 0x33, 0x22, 0x11});
                step(emu, "caxi compare-miss");
                requireRegister(emu, "caxi compare-miss", "r11", 0x11223344L);
                long stored = ((long) emu.readMemoryByte(toAddr(0x3000)) & 0xff)
                        | (((long) emu.readMemoryByte(toAddr(0x3001)) & 0xff) << 8)
                        | (((long) emu.readMemoryByte(toAddr(0x3002)) & 0xff) << 16)
                        | (((long) emu.readMemoryByte(toAddr(0x3003)) & 0xff) << 24);
                if (stored != 0x11223344L || pswBit(emu, 0)) {
                    fail(String.format("caxi compare-miss: mem=0x%x PSW=0x%x",
                            stored, emu.readRegister("PSW").longValue()));
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "di");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("PSW", 0);
                stepInterruptControl(emu, "di interrupt disable", "__disable_irq");
                if (!pswBit(emu, 5)) fail("di did not set PSW.ID");
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "ei");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("PSW", 1L << 5);
                stepInterruptControl(emu, "ei interrupt enable", "__enable_irq");
                if (pswBit(emu, 5)) fail("ei did not clear PSW.ID");
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "rie");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                long originalPsw = (1L << 30) | (1L << 15) | 0x10;
                emu.writeRegister("PSW", originalPsw);
                emu.writeRegister("EBASE", 0x2400);
                step(emu, "rie architectural state");
                requireRegister(emu, "rie architectural state", "PC", 0x2460);
                requireRegister(emu, "rie architectural state", "FEPC", a);
                requireRegister(emu, "rie architectural state", "FEPSW", originalPsw);
                requireRegister(emu, "rie architectural state", "FEIC", 0x60);
                if (!pswBit(emu, 7) || !pswBit(emu, 6) || !pswBit(emu, 5)
                        || pswBit(emu, 30)) {
                    fail("rie did not apply NP/EP/ID/UM exception state");
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "fetrap-3");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("PSW", 1L << 30);
                emu.writeRegister("RBASE", 0x2600);
                step(emu, "fetrap architectural state");
                requireRegister(emu, "fetrap architectural state", "PC", 0x2630);
                requireRegister(emu, "fetrap architectural state", "FEPC", a + 2);
                requireRegister(emu, "fetrap architectural state", "FEIC", 0x33);
                if (!pswBit(emu, 7) || !pswBit(emu, 6) || !pswBit(emu, 5)
                        || pswBit(emu, 30)) {
                    fail("fetrap did not apply NP/EP/ID/UM exception state");
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "ctret");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("CTPC", 0x12345678L);
                emu.writeRegister("CTPSW", 0x1b);
                emu.writeRegister("PSW", 0x123456e0L);
                step(emu, "ctret lower flags");
                requireRegister(emu, "ctret lower flags", "PC", 0x12345678L);
                requireRegister(emu, "ctret lower flags", "PSW", 0x123456fbL);
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "trap-3");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                long originalPsw = (1L << 30) | (1L << 15) | 0x10;
                emu.writeRegister("PSW", originalPsw);
                emu.writeRegister("EBASE", 0x2200);
                step(emu, "trap-3 architectural state");
                requireRegister(emu, "trap-3 architectural state", "PC", 0x2240);
                requireRegister(emu, "trap-3 architectural state", "EIPC", a + 4);
                requireRegister(emu, "trap-3 architectural state", "EIPSW", originalPsw);
                requireRegister(emu, "trap-3 architectural state", "EIIC", 0x43);
                if (!pswBit(emu, 6) || !pswBit(emu, 5) || pswBit(emu, 30)) {
                    fail("trap-3 did not apply EP/ID/UM exception state");
                }
            } finally {
                emu.dispose();
            }
        }

        a = requireCaseAddr(addrs, "eiret");
        if (a >= 0) {
            EmulatorHelper emu = emulator(a);
            try {
                emu.writeRegister("EIPC", 0x12345678L);
                emu.writeRegister("EIPSW", 0x00070031L);
                step(emu, "eiret architectural state");
                requireRegister(emu, "eiret architectural state", "PC", 0x12345678L);
                requireRegister(emu, "eiret architectural state", "PSW", 0x00070031L);
            } finally {
                emu.dispose();
            }
        }

        verifyLdsr(addrs, "ldsr-psw", "PSW", 0x00070031L);
        verifyLdsr(addrs, "ldsr-mcfg0", "MCFG0", 0x12345678L);
        verifyLdsr(addrs, "ldsr-pmr", "PMR", 0x00000055L);
        verifyLdsr(addrs, "ldsr-mcc", "MCC", 0x89abcdefL);
        verifyLdsr(addrs, "ldsr-mpat15", "MPAT15", 0x000000b8L);
        verifyStsr(addrs, "stsr-mcfg0", "MCFG0", 0x12345678L);
        verifyStsr(addrs, "stsr-pmr", "PMR", 0x00000055L);
        verifyStsr(addrs, "stsr-mcc", "MCC", 0x89abcdefL);
        verifyStsr(addrs, "stsr-mpat15", "MPAT15", 0x000000a8L);
        verifyStsr(addrs, "stsr-cdbcr", "CDBCR", 0x00000004L);
    }

    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        if (args.length != 1) {
            throw new IllegalArgumentException("expected absolute manifest.json path");
        }
        String text = Files.readString(Path.of(args[0]));
        // Very small hand-rolled extraction for cases array objects.
        List<Case> cases = Case.parseAll(text);
        println("AssertProcessorFixtureSemantics: cases=" + cases.size());
        java.util.Map<String, Long> addrs = new java.util.HashMap<>();
        for (Case c : cases) {
            addrs.put(c.name, c.addr);
        }

        for (Case c : cases) {
            Address addr = toAddr(c.addr);
            // Clear and disassemble exactly at the fixture address.
            Instruction existing = currentProgram.getListing().getInstructionContaining(addr);
            if (existing != null && !existing.getMinAddress().equals(addr)) {
                currentProgram.getListing().clearCodeUnits(
                    existing.getMinAddress(), existing.getMaxAddress(), false);
            }
            if (currentProgram.getListing().getInstructionAt(addr) == null) {
                disassemble(addr);
            }
            Instruction ins = currentProgram.getListing().getInstructionAt(addr);
            if (ins == null) {
                fail(c.name + ": failed to disassemble at 0x" + Long.toHexString(c.addr));
                continue;
            }
            String mnem = ins.getMnemonicString();
            if (c.mnemonicPrefix != null && (mnem == null || !mnem.startsWith(c.mnemonicPrefix))) {
                fail(c.name + ": mnemonic=" + mnem + " expected prefix " + c.mnemonicPrefix);
            }
            if (c.operandRegister != null) {
                boolean found = false;
                for (int op = 0; op < ins.getNumOperands(); op++) {
                    String rep = ins.getDefaultOperandRepresentation(op);
                    if (c.operandRegister.equals(rep)) {
                        found = true;
                        break;
                    }
                }
                if (!found) {
                    fail(c.name + ": operands do not contain exact register "
                            + c.operandRegister + ": " + ins);
                }
            }
            if (c.operandContains != null) {
                StringBuilder operands = new StringBuilder();
                for (int op = 0; op < ins.getNumOperands(); op++) {
                    if (op != 0) operands.append(", ");
                    operands.append(ins.getDefaultOperandRepresentation(op));
                }
                if (!operands.toString().contains(c.operandContains)) {
                    fail(c.name + ": operands=" + operands
                            + " expected to contain " + c.operandContains);
                }
            }
            Set<String> ops = pcodeOpNames(ins);
            for (String need : c.mustPcodeOps) {
                if (!ops.contains(need)) {
                    fail(c.name + ": missing pcode op " + need + " in " + ops);
                }
            }
            for (String forbid : c.forbidPcodeOps) {
                if (ops.contains(forbid)) {
                    fail(c.name + ": forbidden pcode op " + forbid + " in " + ops);
                }
            }
            if (c.userop != null) {
                String actualUserop = useropName(ins);
                if (!c.userop.equals(actualUserop)) {
                    fail(c.name + ": userop=" + actualUserop + " expected " + c.userop);
                }
            }
            if (c.signExtend != null) {
                if (c.signExtend && !hasSignExtendFromLoad(ins, c.loadSize)) {
                    fail(c.name + ": expected INT_SEXT for signed load; ops=" + ops);
                }
                if (!c.signExtend && c.loadSize > 0 && !hasZeroExtendFromLoad(ins)
                        && !ops.contains("LOAD")) {
                    fail(c.name + ": expected zero-extending load; ops=" + ops);
                }
                if (!c.signExtend && hasSignExtendFromLoad(ins, c.loadSize)
                        && c.mnemonicPrefix != null && c.mnemonicPrefix.contains("u")) {
                    fail(c.name + ": unsigned load unexpectedly sign-extends; ops=" + ops);
                }
            }
            if (c.flow != null) {
                FlowType ft = ins.getFlowType();
                boolean ok = switch (c.flow) {
                    case "CALL" -> ft.isCall();
                    case "RETURN" -> ft.isTerminal() || "RETURN".equalsIgnoreCase(String.valueOf(ft));
                    case "BRANCH" -> ft.isJump();
                    default -> String.valueOf(ft).toUpperCase().contains(c.flow);
                };
                // Also accept CALL_RETURN etc.
                if (!ok) {
                    String s = String.valueOf(ft).toUpperCase();
                    if (c.flow.equals("RETURN") && (s.contains("RETURN") || s.contains("TERMINAL"))) ok = true;
                    if (c.flow.equals("CALL") && s.contains("CALL")) ok = true;
                }
                if (!ok) {
                    fail(c.name + ": flow=" + ft + " expected " + c.flow);
                }
            }
            println(String.format("  [%s] 0x%x %s ops=%s", c.name, c.addr, mnem, ops));
        }

        runExecutionVectors(addrs);

        if (!failures.isEmpty()) {
            throw new IllegalStateException(failures.size() + " fixture failures: "
                    + String.join("; ", failures));
        }
        println("ASSERT processor-fixture: all " + cases.size() + " cases passed");
    }

    private static final class Case {
        String name;
        long addr;
        String mnemonicPrefix;
        String operandRegister;
        List<String> mustPcodeOps = new ArrayList<>();
        String operandContains;
        List<String> forbidPcodeOps = new ArrayList<>();
        Integer loadSize;
        Boolean signExtend;
        String flow;
        String userop;

        static List<Case> parseAll(String text) {
            List<Case> out = new ArrayList<>();
            // Split on case objects inside the cases array by looking for "name":
            int casesIdx = text.indexOf("\"cases\"");
            if (casesIdx < 0) return out;
            int arr = text.indexOf('[', casesIdx);
            int end = text.lastIndexOf(']');
            String body = text.substring(arr + 1, end);
            String[] parts = body.split("\\},\\s*\\{");
            for (String part : parts) {
                String obj = part.trim();
                if (!obj.startsWith("{")) obj = "{" + obj;
                if (!obj.endsWith("}")) obj = obj + "}";
                Case c = new Case();
                c.name = extractString(obj, "name");
                c.addr = extractLong(obj, "addr");
                c.mnemonicPrefix = extractString(obj, "mnemonic_prefix");
                c.operandRegister = extractString(obj, "operand_register");
                c.operandContains = extractString(obj, "operand_contains");
                c.mustPcodeOps = extractStringArray(obj, "must_pcode_ops");
                c.forbidPcodeOps = extractStringArray(obj, "forbid_pcode_ops");
                if (obj.contains("\"load_size\"")) c.loadSize = (int) extractLong(obj, "load_size");
                if (obj.contains("\"sign_extend\"")) c.signExtend = extractBool(obj, "sign_extend");
                c.flow = extractString(obj, "flow");
                c.userop = extractString(obj, "userop");
                out.add(c);
            }
            return out;
        }

        private static String extractString(String obj, String key) {
            String needle = "\"" + key + "\"";
            int i = obj.indexOf(needle);
            if (i < 0) return null;
            int colon = obj.indexOf(':', i);
            int q1 = obj.indexOf('"', colon + 1);
            if (q1 < 0) return null;
            int q2 = obj.indexOf('"', q1 + 1);
            return obj.substring(q1 + 1, q2);
        }

        private static long extractLong(String obj, String key) {
            String needle = "\"" + key + "\"";
            int i = obj.indexOf(needle);
            if (i < 0) return -1;
            int colon = obj.indexOf(':', i);
            int j = colon + 1;
            while (j < obj.length() && Character.isWhitespace(obj.charAt(j))) j++;
            int k = j;
            while (k < obj.length() && (Character.isDigit(obj.charAt(k)) || obj.charAt(k) == '-')) k++;
            return Long.parseLong(obj.substring(j, k));
        }

        private static boolean extractBool(String obj, String key) {
            String needle = "\"" + key + "\"";
            int i = obj.indexOf(needle);
            int colon = obj.indexOf(':', i);
            int j = colon + 1;
            while (j < obj.length() && Character.isWhitespace(obj.charAt(j))) j++;
            return obj.startsWith("true", j);
        }

        private static List<String> extractStringArray(String obj, String key) {
            List<String> out = new ArrayList<>();
            String needle = "\"" + key + "\"";
            int i = obj.indexOf(needle);
            if (i < 0) return out;
            int lb = obj.indexOf('[', i);
            int rb = obj.indexOf(']', lb);
            if (lb < 0 || rb < 0) return out;
            String inner = obj.substring(lb + 1, rb).trim();
            if (inner.isEmpty()) return out;
            for (String piece : inner.split(",")) {
                String s = piece.trim();
                if (s.startsWith("\"") && s.endsWith("\"") && s.length() >= 2) {
                    out.add(s.substring(1, s.length() - 1));
                }
            }
            return out;
        }
    }
}
