#!/usr/bin/env python3
"""Verify target-native Corolla-H motor-control role recovery."""
from __future__ import annotations
import hashlib,json,subprocess,sys,tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
ART=ROOT/'data/generated/corolla_8965H1202000_motor_control.json';EV=ROOT/'data/generated/corolla_8965H1202000_motor_control_decompiler_evidence.json';BUILD=ROOT/'tools/build_corolla_h_motor_control.py';HRAW=ROOT/'community/albinoelephant/raw-20260818/albinoelephant-corolla-2023.20260814-0023/dump_codeflash_00000000_00200000_20260814-025814.bin'
p=f=0
def sha(b):return hashlib.sha256(b).hexdigest()
def ck(n,c,d=''):
 global p,f
 ok=bool(c);p+=ok;f+=not ok;print(f"[{'PASS' if ok else 'FAIL'}][raw_bytes] {n}"+(f' ({d})' if d else ''))
a=json.loads(ART.read_text());e=json.loads(EV.read_text());H=HRAW.read_bytes()[:0x100000];by={int(x['entry'],16):x for x in e['functions']}
print('== deterministic artifact ==')
with tempfile.TemporaryDirectory() as td:
 out=Path(td)/'x.json';r=subprocess.run([sys.executable,str(BUILD),'--out',str(out)],cwd=ROOT,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True);ck('builder exits',r.returncode==0,r.stdout[-400:] if r.returncode else '');ck('report regenerates exactly',r.returncode==0 and out.read_bytes()==ART.read_bytes())
print('\n== compact evidence ==')
ck('H image hash pinned',sha(H)==e['image']['codeflash_sha256']==a['images']['h_sha256']);ck('13 H motor functions compacted',e['function_count']==13==len(e['functions']));ck('all raw H bodies validate',all(sha(H[int(x['entry'],16):int(x['entry'],16)+x['body_size']])==x['body_sha256'] for x in e['functions']));ck('all H decompiler hashes validate',all(sha(x['decompiled_c'].encode())==x['decompiled_c_sha256'] for x in e['functions']))
print('\n== five changed motor roles ==')
exp={'0x00032B80':'0x0002E780','0x00036A44':'0x00032616','0x00038464':'0x00033C70','0x00038554':'0x00033D60','0x0005D18C':'0x00058226'}
ck('all five unresolved motor roles recovered',a['motor_role_closure_count']==5 and {x['reference_entry']:x['target_entry'] for x in a['motor_role_closure']}==exp)
print('\n== calibration state machine ==')
c=a['calibration_state_machine'];ck('S/H calibration state machines are both 1004 bytes',c['sienna_body_size']==c['h_body_size']==1004);ck('state 0x33 calls recovered H main handler',c['sienna_has_state_33_call'] and c['h_has_state_33_call'] and c['h_state_0x33_handler']=='0x0002E780');ck('H main calibration handler grows 1560->1638 bytes',c['sienna_handler_size']==1560 and c['h_handler_size']==1638);ck('H calibration phases publish 0x22 then 0x44',c['h_completion_states']=={'preceding':0x22,'main':0x44} and '= 0x22' in by[0x2E44C]['decompiled_c'] and '= 0x44' in by[0x2E780]['decompiled_c']);ck('0x512 and 0x600 domains still dispatch calibration machine',c['version_dispatch']['domains']==[0x512,0x600] and all(t in by[0x57CEA]['decompiled_c'] for t in ('param_2 == 0x512','param_2 == 0x600','FUN_0002ede6')) and all(t in by[0x57EEE]['decompiled_c'] for t in ('param_2 == 0x512','param_2 == 0x600','FUN_0002ede6')))
print('\n== PI current loops ==')
pi=a['current_pi_pair'];ck('axis A remains exact-size 304-byte analogue',pi['axis_a_body_sizes']==[304,304]);ck('axis B is simplified 404->280 bytes',pi['axis_b_body_sizes']==[404,280]);ck('steady worker preserves B-before-A order',pi['order_preserved'] and pi['sienna_worker_indices']==[15,16] and pi['h_worker_indices']==[11,12]);ck('H A/B share reset and saturation gates',pi['h_shared_reset_gate']);ck('H axis B uses ref-feedback 6BBC-6BAC',all(t.lower().replace('0x','') in by[0x32616]['decompiled_c'].lower() for t in pi['h_axis_b_reference_feedback']));ck('H axis A uses ref-feedback 6BBE-6BB0',all(t.lower().replace('0x','') in by[0x324D4]['decompiled_c'].lower() for t in pi['h_axis_a_reference_feedback']));ck('H gain blocks split A/B at 2D5A4/2D5B4',all(t in by[0x324D4]['decompiled_c'] for t in ('DAT_0002d5a4','DAT_0002d5b0')) and all(t in by[0x32616]['decompiled_c'] for t in ('DAT_0002d5b4','PTR_LAB_0002d5bc')));ck('axis-B internal-state transfer is explicitly bounded','do not transfer Sienna axis-B internal state semantics wholesale' in pi['axis_b_boundary'])
print('\n== inverse rotating-frame pair ==')
inv=a['inverse_rotating_frame'];ck('H inverse transforms are twin 226-byte functions',inv['body_sizes']==[226,226]);ck('inverse formula constants are preserved',inv['formula_tokens_present'] and inv['formula_tokens']==['0x6eda','0x6883','0x8000','0x2000','0x7fff','0x8001']);ck('inverse-transform order is preserved',inv['order_preserved'] and inv['h_worker_indices']==[20,21]);ck('motor0 H inputs/angle/output banks pinned',inv['h_inputs'][0]==['0xFEBE6A80','0xFEBE6A82'] and inv['h_angle_pairs'][0]==['0xFEBE7A54','0xFEBE7A56'] and inv['h_outputs'][0]==['0xFEBE6C78','0xFEBE6C7A','0xFEBE6C7C']);ck('motor1 H inputs/angle/output banks pinned',inv['h_inputs'][1]==['0xFEBE6A84','0xFEBE6A86'] and inv['h_angle_pairs'][1]==['0xFEBE7A60','0xFEBE7A62'] and inv['h_outputs'][1]==['0xFEBE6C80','0xFEBE6C82','0xFEBE6C84'])
print('\n== CH0 orchestration ==')
w=a['ch0_worker'];ck('CH0 worker maps 216->192 bytes',w['sienna_body_size']==216 and w['h_body_size']==192);ck('CH0 wrappers are both 146 bytes',w['wrapper_body_sizes']==[146,146]);ck('H wrapper directly invokes transition and steady workers',all(t in by[0x52DBA]['decompiled_c'] for t in ('FUN_00057fc8(2,uVar4,uVar1)','FUN_00058226(2,uVar2)')));ck('H steady worker uses >0x1FF motor gate and >0x100 duty gate','0x1ff < param_2' in by[0x58226]['decompiled_c'] and '0x100 < param_2' in by[0x58226]['decompiled_c']);ck('H anchor call order is PI-B, PI-A, inverse0, inverse1',all(by[0x58226]['decompiled_c'].index(x+'()') < by[0x58226]['decompiled_c'].index(y+'()') for x,y in zip(w['h_anchor_call_order'],w['h_anchor_call_order'][1:])));ck('transition dispatcher contains same motor anchors',all(x+'()' in by[0x57FC8]['decompiled_c'] for x in w['h_anchor_call_order']))
ck('report closes changed motor residue without flattening target-specific internals',a['static_conclusion']['motor_control_residue_closed'] and 'target-specific' in a['static_conclusion']['boundary'])
print(f'\nResults: {p} passed, {f} failed');raise SystemExit(1 if f else 0)
