#!/usr/bin/env python3
"""Verify target-native Corolla H SecOC/ICU-S residual role recovery."""
from __future__ import annotations
import hashlib,json,subprocess,sys,tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
ART=ROOT/'data/generated/corolla_8965H1202000_secoc_surface.json';EV=ROOT/'data/generated/corolla_8965H1202000_secoc_surface_decompiler_evidence.json';BUILD=ROOT/'tools/build_corolla_h_secoc_surface.py';HRAW=ROOT/'community/albinoelephant/raw-20260818/albinoelephant-corolla-2023.20260814-0023/dump_codeflash_00000000_00200000_20260814-025814.bin'
p=f=0
def sha(b):return hashlib.sha256(b).hexdigest()
def ck(n,c,d=''):
 global p,f
 ok=bool(c);p+=ok;f+=not ok;print(f"[{'PASS' if ok else 'FAIL'}][raw_bytes] {n}"+(f' ({d})' if d else ''))
a=json.loads(ART.read_text());e=json.loads(EV.read_text());H=HRAW.read_bytes()[:0x100000];byh={int(x['target_entry'],16):x for x in e['functions']}
print('== deterministic artifact ==')
with tempfile.TemporaryDirectory() as td:
 out=Path(td)/'x.json';r=subprocess.run([sys.executable,str(BUILD),'--out',str(out)],cwd=ROOT,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True);ck('builder exits',r.returncode==0,r.stdout[-400:] if r.returncode else '');ck('report regenerates exactly',r.returncode==0 and out.read_bytes()==ART.read_bytes())
print('\n== compact evidence ==')
ck('H image hash pinned',sha(H)==e['image']['codeflash_sha256']==a['images']['h_sha256']);ck('42 residual role records are compacted',e['function_count']==42==len(e['functions'])==a['secoc_role_closure_count']);ck('all raw canonical-size target windows validate',all(sha(H[int(x['target_entry'],16):int(x['target_entry'],16)+x['raw_window_size']])==x['raw_window_sha256'] for x in e['functions']));ck('all target-native decompiler hashes validate',all(sha(x['decompiled_c'].encode())==x['decompiled_c_sha256'] for x in e['functions']))
print('\n== ICU-S / CryptoIf core ==')
c=a['icus_cryptoif_core'];ck('25 lower core roles recover at one -0x5C00 island',c['role_count']==25 and c['all_at_single_delta'] and c['delta']==-0x5c00);ck('all 25 core reported body sizes match canonical roles',c['all_reported_body_sizes_match']);ck('command8 adapter calls command8 prepare','FUN_00081262' in byh[0x814a8]['decompiled_c']);ck('command5 adapter calls MAC-generation prepare','FUN_00081e94' in byh[0x820cc]['decompiled_c']);ck('command7 verify adapter calls CMAC-verify prepare','FUN_000822d0' in byh[0x824dc]['decompiled_c']);ck('CryptoIf begin/update preserve generic job chain',byh[0x82f6a]['target_reported_body_size']==50 and byh[0x82f9c]['target_reported_body_size']==12);ck('FIFO/finalizer trio is exact-size relocated family',[byh[x]['target_reported_body_size'] for x in (0x83848,0x838be,0x83910)]==[82,82,60])
print('\n== RX front-end and profile population ==')
r=a['rx_frontend'];ck('H init and ingress roles recovered',r['init']['h']=='0x00088024' and r['indication']['h']=='0x0008818C');ck('H init installs generated slot-4 crypto config',r['init']['installs_slot4_config']);ck('H ingress calls record lookup then secured queue',r['indication']['calls_record_lookup'] and r['indication']['calls_secured_queue'] and r['indication']['body_size']==62);ck('H has exactly three SecOC RX profiles',r['profile_count']==3 and [x['can_id'] for x in r['profiles']]==[0x00f,0x0d7,0x0b6]);ck('H profile PDU IDs are 9/40/42',[x['pdu_id'] for x in r['profiles']]==[9,40,42]);ck('all H profiles share crypto config/job 0',all(x['crypto_config_id']==0 and x['cryptoif_handle']==0 for x in r['profiles']))
print('\n== freshness architecture ==')
fr=a['freshness'];ck('configured get callback is H 896B0',fr['configured_get_callback_set']==[0x896b0]);ck('configured commit callback is H 89758',fr['configured_commit_callback_set']==[0x89758]);ck('get callback dispatches profile lookup + normal/sync reconstruction',fr['get_dispatches_normal_sync']);ck('commit callback dispatches profile lookup + normal/sync commit',fr['commit_dispatches_normal_sync']);ck('normal freshness reconstruct maps to H 89E9A',fr['reconstruct_normal']['h']=='0x00089E9A' and byh[0x89e9a]['target_reported_body_size']==212);ck('sync freshness reconstruct maps to H 89F6E',fr['reconstruct_sync']['h']=='0x00089F6E' and byh[0x89f6e]['target_reported_body_size']==228);ck('normal/sync commits retain 52/78-byte roles',[byh[x]['target_reported_body_size'] for x in (0x8a07a,0x8a130)]==[52,78])
print('\n== application ICU interrupts and test callbacks ==')
i=a['application_icus_isrs'];ck('ICU ISR pair remains 66-byte wrappers',i['same_reported_size']);ck('CH292 ISR calls H interrupt dispatcher','FUN_00081a10' in byh[0x5f3ec]['decompiled_c']);ck('CH293 ISR calls H interrupt dispatcher','FUN_00081a36' in byh[0x5f42e]['decompiled_c']);tc=a['crypto_test_callbacks'];cmpc=byh[0x633a0]['decompiled_c'];ck('command5 result comparator still compares 16 bytes and returns 44/33',tc['result_compare']['compare_length']==16 and '0x10' in cmpc and '0x44' in cmpc and '0x33' in cmpc);ck('key-update completion retains 44/66 terminal states','0x66' in byh[0x63542]['decompiled_c'] and '0x44' in byh[0x63542]['decompiled_c']);ck('command5 completion calls result comparator on success','000633a0' in byh[0x635a2]['decompiled_c'].lower());ck('fragmented callback boundary caveat is explicit','fragmented' in tc['boundary'])
print('\n== protected D7 generated unpacker ==')
d=a['d7_unpacker'];ck('H D7 SecOC record routes to PDU 40',d['h_secoc_record_pdu_id']==40);ck('PDU 40 owns configured signals 240..247',d['h_pdu40_signal_ids']==list(range(240,248)));ck('H D7 scalar unpacker is 468FA and reads 240/243/246',d['h']=='0x000468FA' and sorted(d['h_scalar_receive_signal_ids'])==[240,243,246]);ck('H D7 unpacker is regenerated 194->140 bytes',d['sienna_body_size']==194 and d['h_reported_body_size']==140);ck('D7 role transfer does not transfer Sienna signal IDs','regenerates the signal population' in d['interpretation'])
print('\n== conclusion boundary ==')
sc=a['static_conclusion'];ck('all 42 SecOC/ICU-S residual roles are closed',sc['all_42_secoc_icus_residual_roles_recovered']);ck('profile population difference remains explicit',sc['h_profile_population_changed']);ck('target-specific key/profile boundary remains explicit','protected key contents remain H-specific' in sc['boundary'])
print(f'\nResults: {p} passed, {f} failed');raise SystemExit(1 if f else 0)
