#!/usr/bin/env python3
"""Verify the stock command-5 terminal-result -> Dem/DTC observation side channel.

This is deliberately narrower than a signing-oracle claim:

* RID 0x100F + CAN 0x01B..0x01F can reach command 5 without Dcm SA.
* A successful command whose 16-byte result mismatches the chosen expected value
  and a command-5 execution failure both collapse to bank state 0x44.
* That terminal failure state sets FEBE5097=0x5A; the generated application
  monitor reports Dem event 0xCC with value 0x32 exactly once per monitor latch.
* Event 0xCC maps to enabled DTC-table index 133 / DTC 0x00D317, and the no-SA
  SID-0x19 subfunction-02 path enumerates enabled DTCs whose generated status
  intersects the tester's supported status mask.
* The 16 generated bytes at FEBE51AA..FEBE51B9 remain private: the tracked whole-
  image direct-reference census contains no DTC/snapshot/diagnostic reader of
  that range beyond the local 16-byte comparison.

Therefore stock firmware exposes an externally observable *terminal negative
outcome* for the command-5 test bank. Once successful command execution is
independently established, that negative outcome can distinguish a wrong full
expected result from equality; by itself it cannot distinguish command failure
from result mismatch and is not a byte-output or key-recovery oracle.

Runtime reset machinery can return the crypto-test bank to active=0, but whether
an external tester can deliberately force the required application transition is
left bounded rather than inferred here.
"""
from __future__ import annotations

import csv
import hashlib
import json
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CF = (ROOT / "firmware" / "RH850_P1M-E_CodeFlash.bin").read_bytes()
passed = failed = 0


def check(name: str, condition: bool, detail: str = "") -> None:
    global passed, failed
    if condition:
        passed += 1
        print(f"[PASS] {name}")
    else:
        failed += 1
        print(f"[FAIL] {name}" + (f" ({detail})" if detail else ""))


def body_hash(addr: int, size: int) -> str:
    return hashlib.sha256(CF[addr : addr + size]).hexdigest()


def u32(addr: int) -> int:
    return struct.unpack_from("<I", CF, addr)[0]


print("== stock bank-1 activation / comparison contract ==")
with (ROOT / "data" / "application_routine_control_surface.csv").open(newline="") as handle:
    routine_rows = list(csv.DictReader(handle))
r100f = next(r for r in routine_rows if r["rid"].lower() == "0x100f")
check("RID 0x100F is enabled and SecurityAccess-free",
      r100f["enabled"] == "1" and r100f["security_level_count"] == "0")
check("RID 0x100F is start-only, zero-payload, sessions 1/2/3",
      r100f["control_type1_supported"] == "1"
      and r100f["control_type3_supported"] == "0"
      and r100f["control_type1_input_bytes"] == "0"
      and r100f["effective_routine_control_sessions"] == "1,2,3")
check("RID 0x100F action wrapper remains 0x8A782",
      r100f["action_callback"].lower() == "0x8a782")
check("bank-1 activator body pinned",
      body_hash(0x69018, 42) == "12088375d109e4753b8e88ffeb0edef82691229791ab8505f4ffab62e106f1fd")
check("16-byte expected-vs-generated comparison body pinned",
      body_hash(0x69068, 38) == "9d34d1c1fff4dd34ac338c530e539f3663362db2c6ab4758065f7ac70c062173")
check("comparison returns 0x44 immediately on first unequal byte",
      CF[0x6907A:0x69084] == bytes.fromhex("f391c205205644007f00"))

print("\n== failure/mismatch -> Dem event 0xCC ==")
check("bank-1 finalizer body pinned",
      body_hash(0x68D0E, 46) == "8c7e6305f209fd80615fbd78b2c1ba08fad882f1cf0bf202b15499e7e9411bd9")
check("terminal 0x44 stores mismatch/failure latch 0x5A at FEBE5097",
      CF[0x68D22:0x68D32] == bytes.fromhex("0106bcffea0520965a001f9a44979798"))
check("monitor body pins FEBE5097==0x5A -> event 0xCC,value 0x32",
      body_hash(0x55F1C, 48) == "27b8dcab40bb1348bbff03f0cebced4932e416cbf08630ea9dc8410e5b5c2383")
check("monitor materializes event 0xCC / value 0x32 before Dem reporter",
      CF[0x55F34:0x55F40] == bytes.fromhex("2036cc00203e3200bfffaeac"))
check("Dem reporter body pinned",
      body_hash(0x50BEA, 144) == "1979b67cfc31449a61bb1b664d512efbc0adda777b40539a42c320cbf969013d")

EVENT_TABLE = 0x2FDDC
EVENT_SIZE = 8
DTC_TABLE = 0x309DC
DTC_SIZE = 8
event = CF[EVENT_TABLE + 0xCC * EVENT_SIZE : EVENT_TABLE + (0xCC + 1) * EVENT_SIZE]
check("event 0xCC record is exact enabled aggregation mapping",
      event == bytes.fromhex("4200850000000000"), event.hex())
check("event 0xCC maps to DTC-table index 133", event[2] == 0x85)
dtc = struct.unpack_from("<BHBI", CF, DTC_TABLE + event[2] * DTC_SIZE)
check("DTC index 133 is enabled DTC 0xD317 / failure type 0x57",
      dtc == (0x57, 0xD317, 0, 1), repr(dtc))

print("\n== Dem aggregation -> no-SA SID 0x19 observability ==")
# Pin the event->DTC aggregation/status machinery rather than relying on names.
for addr, size, digest, label in (
    (0x51268, 254, "31dfd2b9ec7c0348d07b98db9e466ab4472cda652983bfc1d6d3839098919136", "event activation aggregator"),
    (0x50F56, 310, "7ccafc3fa2fbb5c8535e9d4ab7ed651a3f003ce0ed0b5264bcb6f31bd1506dfe", "dirty event-to-DTC aggregator"),
    (0x5159E, 178, "2451d19671722f2004fabaddab6853d8476313635a647d673afafb5e601683db", "DTC status-byte generator"),
    (0x5175A, 90, "e6eb1915244ed8f27a8918fc47b1855f8624b30a26394e28835ffe5002430e9d", "DTC enumerator"),
    (0x4CA18, 12, "88d3731fd9e35db49f7159acac4a89d210ccf7fa2dddc08fe8bde8e6e1fbcb64", "supported-status-mask getter"),
    (0x4CA24, 18, "f804bf6b9c0cce1869f6e9b1f0a5d53e3c3e7b7ceb4caa58650fdc3e730d8534", "tester-mask setter"),
    (0x4CA5C, 88, "e22366aed685b580d028dd97eb0db0414d99c1ab9f87f2bbcbfcd69b7fe50cef", "SID19 DTC iterator wrapper"),
):
    check(f"{label} body pinned", body_hash(addr, size) == digest)
check("SID19 supported-status mask is literal 0xB9",
      CF[0x4CA18:0x4CA24] == bytes.fromhex("06f0200eb9ff0052800b7f00"))
check("SID19 tester mask is ANDed with 0xB9 before enumeration",
      CF[0x4CA24:0x4CA30] == bytes.fromhex("c60eb90024f64cc9840b0052"))
check("DTC iterator tests requested mask against generated status before returning DTC",
      CF[0x5177C:0x517A8].find(bytes.fromhex("5309")) >= 0
      and CF[0x5178E:0x5179C].find(struct.pack("<I", DTC_TABLE)) >= 0)

with (ROOT / "data" / "application_diagnostic_map.csv").open(newline="") as handle:
    diag_rows = list(csv.DictReader(handle))
sid19 = next(r for r in diag_rows if r["sid"].lower() == "0x19")
check("SID 0x19 has no configured SecurityAccess entries", sid19["security_allow_count"] == "0")
check("SID 0x19 permits default and extended sessions", sid19["session_allow_list"] == "1,3")
check("SID 0x19 config includes report-by-status-mask subfunction 0x02",
      "02" in sid19["subfunctions"].lower())

print("\n== generated bytes remain private ==")
refs: list[tuple[str, str, str, str]] = []
with (ROOT / "data" / "generated" / "decompilations.jsonl").open() as handle:
    for line in handle:
        row = json.loads(line)
        for ref in row.get("data_references", []):
            try:
                target = int(ref.get("to_addr", "0"), 16)
            except (TypeError, ValueError):
                continue
            if 0xFEBE51AA <= target <= 0xFEBE51B9:
                refs.append((row["entry_addr"], row["name"], ref["ref_type"], ref["to_addr"]))
readers = {(entry, name) for entry, name, kind, _ in refs if kind == "READ"}
check("only local compare directly reads generated command-5 result bytes",
      readers == {("0x00069068", "icus_command5_test_result_compare")}, repr(sorted(readers)))
check("no DTC/snapshot/UDS function directly reads FEBE51AA..FEBE51B9",
      all(not (kind == "READ" and entry != "0x00069068") for entry, _, kind, _ in refs))

print("\n== repeatability is explicitly bounded ==")
check("full crypto-test reset clears bank-1 active byte",
      CF[0x68006:0x6800A] == bytes.fromhex("44078f98"))
check("runtime cyclic resets full crypto-test state only on reset-request value 0xA5",
      body_hash(0x68C0C, 122) == "b4fd8a1c8f6d9de83d08aefc246c1f9285dbab547bf6d71f4a0bad252d6096ef"
      and CF[0x68C10:0x68C20] == bytes.fromhex("a4ef8d981d065bffca05bfffb4f3850d"))
check("application transition helper can request 0xA5 reset but is not an external-reset proof",
      body_hash(0x4F93C, 94) == "973db76a6c1bd3f07199137c1e6cb44bd4369a4f3c3c0da26fe0196d8dea3fb1"
      and CF[0x4F95E:0x4F968] == bytes.fromhex("00e22036a50081ff7a97"))

print(f"\nSummary: {passed} passed, {failed} failed")
sys.exit(1 if failed else 0)
