//@author kaikozlov
//@category Seed
// Parse and seed the exact F33 241-record application RDBI table at 0x2928C.
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.*;
import ghidra.program.model.symbol.SourceType;
import java.util.*;
public class SeedCamryF33Diagnostics extends GhidraScript {
  private Function ensure(long v,String name) throws Exception { Address a=toAddr(v); Listing l=currentProgram.getListing(); Instruction c=l.getInstructionContaining(a); if(c!=null&&!c.getMinAddress().equals(a)) l.clearCodeUnits(c.getMinAddress(),c.getMaxAddress(),false); CodeUnit u=l.getCodeUnitContaining(a); if(u!=null&&!(u instanceof Instruction)) l.clearCodeUnits(u.getMinAddress(),u.getMaxAddress(),false); if(l.getInstructionAt(a)==null&&!disassemble(a)) throw new IllegalStateException("disassembly failed "+a); Function f=currentProgram.getFunctionManager().getFunctionAt(a); if(f==null) f=createFunction(a,name); if(f==null) throw new IllegalStateException("function creation failed "+a); if(f.getName().startsWith("FUN_")||f.getName().startsWith("f33_rdbi_")) f.setName(name,SourceType.USER_DEFINED); return f; }
  private String name(int did){ return switch(did){ case 0x1035->"did_1035_steering_wheel_torque"; case 0x1036->"did_1036_steering_angle_velocity"; case 0x1037->"did_1037_steering_angle"; case 0x1151->"did_1151_motor_actual_current_q_axis"; case 0x1152->"did_1152_command_value_current_q_axis"; case 0x1153->"did_1153_motor_actual_current_2_d_axis"; case 0x1154->"did_1154_command_value_current_2_d_axis"; case 0x1155->"did_1155_motor_rotation_angle"; case 0x1156->"did_1156_final_motor_current_limited_q_axis"; case 0x1185->"did_1185_can_vehicle_speed_sp1"; case 0x1C02->"did_1c02_command_value_torque"; case 0x1C03->"did_1c03_control_state_information"; case 0x1C05->"did_1c05_1c0c_asic_state_information"; default->String.format("f33_rdbi_%04x_callback",did); }; }
  @Override public void run() throws Exception { long base=0x2928CL; int count=241; int first=currentProgram.getMemory().getShort(toAddr(base))&0xffff; int last=currentProgram.getMemory().getShort(toAddr(base+(count-1)*16L))&0xffff; if(first!=0x0101||last!=0xF18C) throw new IllegalStateException(String.format("RDBI geometry drift first=%04x last=%04x",first,last)); LinkedHashMap<Long,Integer> cb=new LinkedHashMap<>(); for(int i=0;i<count;i++){ long r=base+i*16L; int did=currentProgram.getMemory().getShort(toAddr(r))&0xffff; long fn=currentProgram.getMemory().getInt(toAddr(r+4))&0xffffffffL; if(did==0||fn==0||fn>=0x100000L) throw new IllegalStateException(String.format("bad RDBI record %d did=%04x fn=%08x",i,did,fn)); cb.putIfAbsent(fn,did); } for(var e:cb.entrySet()) ensure(e.getKey(),name(e.getValue())); if(cb.size()!=195) throw new IllegalStateException("RDBI callback count drift "+cb.size()); println("SeedCamryF33Diagnostics: 241 records / 195 unique callbacks from 0x2928C"); }
}
