#!/usr/bin/env python3
"""Regenerate the application COM Tx signal map from the recovered static model.

The semantic row model is curated, while all structural boundaries that make the
three long-tail conclusions possible are revalidated directly against CodeFlash
before output: packer bodies, COM descriptors, CanIf post-packer route flags,
and the checksum callback body/pointers.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
from pathlib import Path
import struct

REPO = Path(__file__).resolve().parents[1]
CF_PATH = REPO / "firmware" / "RH850_P1M-E_CodeFlash.bin"
DEFAULT_OUT = REPO / "data" / "application_tx_map.csv"
FIELDNAMES = ['tx_pdu_id', 'can_id', 'message_name', 'length', 'cycle_ticks', 'signal_id', 'wire_field', 'source_kind', 'source', 'static_role', 'packer']
ROWS = [{'tx_pdu_id': '0',
  'can_id': '0x260',
  'message_name': 'STEER_TORQUE_SENSOR',
  'length': '8',
  'cycle_ticks': '4',
  'signal_id': '0',
  'wire_field': 'B0[7]',
  'source_kind': 'ram',
  'source': '0xFEBE8094',
  'static_role': 'constant-clear in recovered producer graph; public DBC location STEER_OVERRIDE',
  'packer': '0x4BCEE'},
 {'tx_pdu_id': '0',
  'can_id': '0x260',
  'message_name': 'STEER_TORQUE_SENSOR',
  'length': '8',
  'cycle_ticks': '4',
  'signal_id': '1',
  'wire_field': 'B0[4]',
  'source_kind': 'ram',
  'source': '0xFEBE8096',
  'static_role': 'composite initialization/validity flag; public DBC STEER_ANGLE_INITIALIZING',
  'packer': '0x4BCEE'},
 {'tx_pdu_id': '0',
  'can_id': '0x260',
  'message_name': 'STEER_TORQUE_SENSOR',
  'length': '8',
  'cycle_ticks': '4',
  'signal_id': '2',
  'wire_field': 'B0[3]',
  'source_kind': 'ram',
  'source': '0xFEBE8098',
  'static_role': 'debounced steering-control consistency status',
  'packer': '0x4BCEE'},
 {'tx_pdu_id': '0',
  'can_id': '0x260',
  'message_name': 'STEER_TORQUE_SENSOR',
  'length': '8',
  'cycle_ticks': '4',
  'signal_id': '3',
  'wire_field': 'B0[2]',
  'source_kind': 'ram',
  'source': '0xFEBE8099',
  'static_role': 'operational-mode/status inhibit A',
  'packer': '0x4BCEE'},
 {'tx_pdu_id': '0',
  'can_id': '0x260',
  'message_name': 'STEER_TORQUE_SENSOR',
  'length': '8',
  'cycle_ticks': '4',
  'signal_id': '4',
  'wire_field': 'B0[1]',
  'source_kind': 'ram',
  'source': '0xFEBE809A',
  'static_role': 'operational-mode/status inhibit B',
  'packer': '0x4BCEE'},
 {'tx_pdu_id': '0',
  'can_id': '0x260',
  'message_name': 'STEER_TORQUE_SENSOR',
  'length': '8',
  'cycle_ticks': '4',
  'signal_id': '5',
  'wire_field': 'B0[0]',
  'source_kind': 'ram',
  'source': '0xFEBE809B',
  'static_role': 'thresholded motor-feedback magnitude status',
  'packer': '0x4BCEE'},
 {'tx_pdu_id': '0',
  'can_id': '0x260',
  'message_name': 'STEER_TORQUE_SENSOR',
  'length': '8',
  'cycle_ticks': '4',
  'signal_id': '6',
  'wire_field': 'B1..B2 BE16',
  'source_kind': 'ram',
  'source': '0xFEBE810A',
  'static_role': 'scaled/clamped sensor torque; public DBC STEER_TORQUE_DRIVER',
  'packer': '0x4BCEE'},
 {'tx_pdu_id': '0',
  'can_id': '0x260',
  'message_name': 'STEER_TORQUE_SENSOR',
  'length': '8',
  'cycle_ticks': '4',
  'signal_id': '7',
  'wire_field': 'B3..B4 BE16',
  'source_kind': 'ram',
  'source': '0xFEBE810E',
  'static_role': 'saturated signed steering-control estimate; public DBC STEER_ANGLE',
  'packer': '0x4BCEE'},
 {'tx_pdu_id': '0',
  'can_id': '0x260',
  'message_name': 'STEER_TORQUE_SENSOR',
  'length': '8',
  'cycle_ticks': '4',
  'signal_id': '8',
  'wire_field': 'B5..B6 BE16',
  'source_kind': 'ram',
  'source': '0xFEBE8110',
  'static_role': 'scaled motor-feedback torque estimate; public DBC STEER_TORQUE_EPS',
  'packer': '0x4BCEE'},
 {'tx_pdu_id': '0',
  'can_id': '0x260',
  'message_name': 'STEER_TORQUE_SENSOR',
  'length': '8',
  'cycle_ticks': '4',
  'signal_id': '9',
  'wire_field': 'B7',
  'source_kind': 'canif_checksum',
  'source': '0x7FEAC',
  'static_role': 'Toyota additive checksum: post-packer CanIf callback sums CAN-ID bytes + DLC + payload[0:-1] into '
                 'final byte',
  'packer': '0x4BCEE'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '10',
  'wire_field': 'B0[7]',
  'source_kind': 'ram',
  'source': '0xFEBE809C',
  'static_role': 'constant-zero EPS_STATUS prefix bit',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '11',
  'wire_field': 'B0[6]',
  'source_kind': 'ram',
  'source': '0xFEBE80B4',
  'static_role': 'constant-zero EPS_STATUS prefix bit',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '12',
  'wire_field': 'B0[5]',
  'source_kind': 'ram',
  'source': '0xFEBE809D',
  'static_role': 'constant-zero EPS_STATUS prefix bit',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '13',
  'wire_field': 'B0[4]',
  'source_kind': 'constant',
  'source': '0',
  'static_role': 'constant zero',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '14',
  'wire_field': 'B0[2]',
  'source_kind': 'ram',
  'source': '0xFEBE809E',
  'static_role': 'IPAS_STATE bit2; constant zero in runtime producer',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '15',
  'wire_field': 'B0[1]',
  'source_kind': 'ram',
  'source': '0xFEBE809F',
  'static_role': 'IPAS_STATE bit1; constant zero in runtime producer',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '16',
  'wire_field': 'B0[0]',
  'source_kind': 'ram',
  'source': '0xFEBE80A0',
  'static_role': 'IPAS_STATE bit0; constant zero in runtime producer',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '17',
  'wire_field': 'B1[7]',
  'source_kind': 'ram',
  'source': '0xFEBE80A4',
  'static_role': 'LTA_STATE bit4; internal status aggregate',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '18',
  'wire_field': 'B1[6]',
  'source_kind': 'ram',
  'source': '0xFEBE80A6',
  'static_role': 'LTA_STATE bit3; timeout/recovery status',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '19',
  'wire_field': 'B1[5]',
  'source_kind': 'ram',
  'source': '0xFEBE80A8',
  'static_role': 'LTA_STATE bit2; active-state latch',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '20',
  'wire_field': 'B1[4]',
  'source_kind': 'ram',
  'source': '0xFEBE80AA',
  'static_role': 'LTA_STATE bit1; multi-condition status aggregate',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '21',
  'wire_field': 'B1[3]',
  'source_kind': 'ram',
  'source': '0xFEBE80AC',
  'static_role': 'LTA_STATE bit0; gated base-eligibility status',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '22',
  'wire_field': 'B1[2:0] || B2',
  'source_kind': 'constant',
  'source': '0',
  'static_role': 'constant zero 11-bit field',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '23',
  'wire_field': 'B3[7]',
  'source_kind': 'ram',
  'source': '0xFEBE80A1',
  'static_role': 'LKA_STATE bit6; constant zero in runtime producer',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '24',
  'wire_field': 'B3[6]',
  'source_kind': 'ram',
  'source': '0xFEBE80A2',
  'static_role': 'LKA_STATE bit5; constant zero in runtime producer',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '25',
  'wire_field': 'B3[5]',
  'source_kind': 'ram',
  'source': '0xFEBE80A3',
  'static_role': 'LKA_STATE bit4; internal status aggregate',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '26',
  'wire_field': 'B3[4]',
  'source_kind': 'ram',
  'source': '0xFEBE80A5',
  'static_role': 'LKA_STATE bit3; transient recovery latch',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '27',
  'wire_field': 'B3[3]',
  'source_kind': 'ram',
  'source': '0xFEBE80A7',
  'static_role': 'LKA_STATE bit2; active-state latch',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '28',
  'wire_field': 'B3[2]',
  'source_kind': 'ram',
  'source': '0xFEBE80A9',
  'static_role': 'LKA_STATE bit1; timeout/availability status',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '29',
  'wire_field': 'B3[1]',
  'source_kind': 'ram',
  'source': '0xFEBE80AB',
  'static_role': 'LKA_STATE bit0; gated base-eligibility status',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '30',
  'wire_field': 'B3[0]',
  'source_kind': 'ram',
  'source': '0xFEBE80AD',
  'static_role': 'TYPE; constant zero in runtime producer',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '31',
  'wire_field': 'B4[7]',
  'source_kind': 'ram',
  'source': '0xFEBE80AE',
  'static_role': 'steering-control threshold status',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '32',
  'wire_field': 'B4[6]',
  'source_kind': 'ram',
  'source': '0xFEBE80AF',
  'static_role': 'steering-control limiter status',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '33',
  'wire_field': 'B4[5]',
  'source_kind': 'ram',
  'source': '0xFEBE80B0',
  'static_role': 'steering-control transition latch',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '34',
  'wire_field': 'B4[4:3]',
  'source_kind': 'ram',
  'source': '0xFEBE80B1',
  'static_role': 'steering-control transition code',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '35',
  'wire_field': 'B5',
  'source_kind': 'ram',
  'source': '0xFEBE80B2',
  'static_role': 'constant 0xFF byte in runtime producer',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '36',
  'wire_field': 'B6',
  'source_kind': 'ram',
  'source': '0xFEBE80B3',
  'static_role': 'constant 0xFF byte in runtime producer',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '1',
  'can_id': '0x262',
  'message_name': 'EPS_STATUS',
  'length': '8',
  'cycle_ticks': '8',
  'signal_id': '37',
  'wire_field': 'B7',
  'source_kind': 'canif_checksum',
  'source': '0x7FEAC',
  'static_role': 'Toyota additive checksum: post-packer CanIf callback sums CAN-ID bytes + DLC + payload[0:-1] into '
                 'final byte',
  'packer': '0x4BE24'},
 {'tx_pdu_id': '2',
  'can_id': '0x351',
  'message_name': 'APP_TX_351',
  'length': '4',
  'cycle_ticks': '200',
  'signal_id': '38',
  'wire_field': 'B2[7:5]',
  'source_kind': 'ram',
  'source': '0xFEBE80B8',
  'static_role': 'filtered plausibility-monitor status code; system-gated override=7',
  'packer': '0x4C25C'},
 {'tx_pdu_id': '2',
  'can_id': '0x351',
  'message_name': 'APP_TX_351',
  'length': '4',
  'cycle_ticks': '200',
  'signal_id': '39',
  'wire_field': 'B2[4]',
  'source_kind': 'ram',
  'source': '0xFEBE80B9',
  'static_role': 'system-gated plausibility-status override flag',
  'packer': '0x4C25C'},
 {'tx_pdu_id': '3',
  'can_id': '0x394',
  'message_name': 'APP_TX_394',
  'length': '3',
  'cycle_ticks': '60',
  'signal_id': '40',
  'wire_field': 'B0[6:4]',
  'source_kind': 'ram',
  'source': '0xFEBE80BA',
  'static_role': 'state-table tuple byte0',
  'packer': '0x4C158'},
 {'tx_pdu_id': '3',
  'can_id': '0x394',
  'message_name': 'APP_TX_394',
  'length': '3',
  'cycle_ticks': '60',
  'signal_id': '41',
  'wire_field': 'B0[1:0]',
  'source_kind': 'ram',
  'source': '0xFEBE80C2',
  'static_role': 'coarse 1..16 internal-state class code',
  'packer': '0x4C158'},
 {'tx_pdu_id': '3',
  'can_id': '0x394',
  'message_name': 'APP_TX_394',
  'length': '3',
  'cycle_ticks': '60',
  'signal_id': '42',
  'wire_field': 'B1[7:6]',
  'source_kind': 'ram',
  'source': '0xFEBE80BD',
  'static_role': 'state-table tuple byte4',
  'packer': '0x4C158'},
 {'tx_pdu_id': '3',
  'can_id': '0x394',
  'message_name': 'APP_TX_394',
  'length': '3',
  'cycle_ticks': '60',
  'signal_id': '43',
  'wire_field': 'B1[2:0]',
  'source_kind': 'ram',
  'source': '0xFEBE80BE',
  'static_role': 'state-table tuple byte1',
  'packer': '0x4C158'},
 {'tx_pdu_id': '3',
  'can_id': '0x394',
  'message_name': 'APP_TX_394',
  'length': '3',
  'cycle_ticks': '60',
  'signal_id': '44',
  'wire_field': 'B2[3:1]',
  'source_kind': 'ram',
  'source': '0xFEBE80BF',
  'static_role': 'state-table tuple byte2',
  'packer': '0x4C158'},
 {'tx_pdu_id': '3',
  'can_id': '0x394',
  'message_name': 'APP_TX_394',
  'length': '3',
  'cycle_ticks': '60',
  'signal_id': '45',
  'wire_field': 'B2[0]',
  'source_kind': 'ram',
  'source': '0xFEBE80C1',
  'static_role': 'state-table tuple byte3',
  'packer': '0x4C158'},
 {'tx_pdu_id': '4',
  'can_id': '0x4A3',
  'message_name': 'APP_TX_4A3',
  'length': '8',
  'cycle_ticks': '100',
  'signal_id': '46',
  'wire_field': 'B0',
  'source_kind': 'ram',
  'source': '0xFEBE80C3',
  'static_role': 'initialization/validity flag OR 0x20',
  'packer': '0x4BB1E'},
 {'tx_pdu_id': '4',
  'can_id': '0x4A3',
  'message_name': 'APP_TX_4A3',
  'length': '8',
  'cycle_ticks': '100',
  'signal_id': '47',
  'wire_field': 'B1',
  'source_kind': 'ram',
  'source': '0xFEBE80C4',
  'static_role': 'CAN 0x025 signal221 signed12 mirror bits11:8',
  'packer': '0x4BB1E'},
 {'tx_pdu_id': '4',
  'can_id': '0x4A3',
  'message_name': 'APP_TX_4A3',
  'length': '8',
  'cycle_ticks': '100',
  'signal_id': '48',
  'wire_field': 'B2',
  'source_kind': 'ram',
  'source': '0xFEBE80C5',
  'static_role': 'CAN 0x025 signal221 signed12 mirror bits7:0',
  'packer': '0x4BB1E'},
 {'tx_pdu_id': '4',
  'can_id': '0x4A3',
  'message_name': 'APP_TX_4A3',
  'length': '8',
  'cycle_ticks': '100',
  'signal_id': '49',
  'wire_field': 'B3',
  'source_kind': 'ram',
  'source': '0xFEBE80C6',
  'static_role': 'clamped signed12 delta (CAN 0x025 s221 - CAN 0x64F s289) bits11:8',
  'packer': '0x4BB1E'},
 {'tx_pdu_id': '4',
  'can_id': '0x4A3',
  'message_name': 'APP_TX_4A3',
  'length': '8',
  'cycle_ticks': '100',
  'signal_id': '50',
  'wire_field': 'B4',
  'source_kind': 'ram',
  'source': '0xFEBE80C7',
  'static_role': 'clamped signed12 delta (CAN 0x025 s221 - CAN 0x64F s289) bits7:0',
  'packer': '0x4BB1E'},
 {'tx_pdu_id': '4',
  'can_id': '0x4A3',
  'message_name': 'APP_TX_4A3',
  'length': '8',
  'cycle_ticks': '100',
  'signal_id': '51',
  'wire_field': 'B5',
  'source_kind': 'ram',
  'source': '0xFEBE80C8',
  'static_role': 'signed-byte conversion of CAN 0x260 driver-torque staging / 10',
  'packer': '0x4BB1E'},
 {'tx_pdu_id': '4',
  'can_id': '0x4A3',
  'message_name': 'APP_TX_4A3',
  'length': '8',
  'cycle_ticks': '100',
  'signal_id': '52',
  'wire_field': 'B6',
  'source_kind': 'ram',
  'source': '0xFEBE80C9',
  'static_role': 'CAN 0x260 EPS-torque staging mirror high byte',
  'packer': '0x4BB1E'},
 {'tx_pdu_id': '4',
  'can_id': '0x4A3',
  'message_name': 'APP_TX_4A3',
  'length': '8',
  'cycle_ticks': '100',
  'signal_id': '53',
  'wire_field': 'B7',
  'source_kind': 'ram',
  'source': '0xFEBE80CA',
  'static_role': 'CAN 0x260 EPS-torque staging mirror low byte',
  'packer': '0x4BB1E'},
 {'tx_pdu_id': '5',
  'can_id': '0x4C8',
  'message_name': 'APP_TX_4C8',
  'length': '8',
  'cycle_ticks': '196',
  'signal_id': '54',
  'wire_field': 'B0',
  'source_kind': 'constant',
  'source': '9',
  'static_role': 'constant 0x09',
  'packer': '0x4BC54'},
 {'tx_pdu_id': '5',
  'can_id': '0x4C8',
  'message_name': 'APP_TX_4C8',
  'length': '8',
  'cycle_ticks': '196',
  'signal_id': '55',
  'wire_field': 'B1[7]',
  'source_kind': 'constant',
  'source': '0',
  'static_role': 'constant zero',
  'packer': '0x4BC54'},
 {'tx_pdu_id': '5',
  'can_id': '0x4C8',
  'message_name': 'APP_TX_4C8',
  'length': '8',
  'cycle_ticks': '196',
  'signal_id': '56',
  'wire_field': 'B2..B3 BE16',
  'source_kind': 'constant',
  'source': '0',
  'static_role': 'constant zero',
  'packer': '0x4BC54'},
 {'tx_pdu_id': '5',
  'can_id': '0x4C8',
  'message_name': 'APP_TX_4C8',
  'length': '8',
  'cycle_ticks': '196',
  'signal_id': '57',
  'wire_field': 'B4..B7',
  'source_kind': 'default_only',
  'source': '0',
  'static_role': 'initial/default zero only in this calibration; packer omits field and all enabled pre/post-transmit '
                 'transforms are absent for PDU 5',
  'packer': '0x4BC54'}]

PACKER_HASHES = {
    (0x4BCEE, 306): "bc9f9430d8e8f59bf010286e425df101ac480a738ac220455a82a6c4c7636c8b",
    (0x4BE24, 816): "0c6150b05372cece5a32c1fc41efc7782d4f0fef7f201cb2673662203b651152",
    (0x4C25C, 136): "7b112b649674374a6ad7be424c8c8b748b8eedb28b73f8b622818157ef0946e7",
    (0x4C158, 256): "99f1648cc628ba9d4fc775415d6ac97ef9ddd9243e11c68b679a1af495b16d10",
    (0x4BB1E, 306): "bcd3ccc9fafb4bbb9fd21e173d2225527baf5104c8c29729612247e3cfb8da0a",
    (0x4BC54, 150): "d24846f017aee98543e1c2f3c30ea4226503fb0e41876749073f7321fddd7477",
}
CHECKSUM_SHA256 = "0e077cd8d1f3c22b7fe2c1478e98a44e2d05f0c7febfa45e9385a5181607c8f1"


def u32(cf: bytes, off: int) -> int:
    return struct.unpack_from("<I", cf, off)[0]


def validate(cf: bytes) -> None:
    for (off, size), expected in PACKER_HASHES.items():
        got = hashlib.sha256(cf[off:off + size]).hexdigest()
        if got != expected:
            raise SystemExit(f"packer body mismatch at {off:#x}: {got}")
    if list(cf[0x21FE0:0x21FE6]) != [1, 1, 0, 0, 0, 0]:
        raise SystemExit("unexpected COM-to-CanIf post-packer route flags")
    if u32(cf, 0x21900) != 0x800D2:
        raise SystemExit("unexpected CanIf pre-enqueue hook")
    if u32(cf, 0x2194C) != 0x7FEAC:
        raise SystemExit("unexpected controller-0 post-packer callback")
    got = hashlib.sha256(cf[0x7FEAC:0x7FEF2]).hexdigest()
    if got != CHECKSUM_SHA256:
        raise SystemExit(f"checksum callback body mismatch: {got}")
    # All six COM PDU descriptors have flags 0x03: no COM-level 0x10/0x20
    # pre-transmit transform path is enabled. This is especially material to
    # the signal-57 default-only negative on PDU 5 / CAN 0x4C8.
    pdu = struct.Struct("<HBBHBB")
    if [pdu.unpack_from(cf, 0x2273C + pdu.size*i)[5] for i in range(6)] != [3]*6:
        raise SystemExit("unexpected COM Tx PDU flags")
    if cf[0x221DC + 31 + 4:0x221DC + 31 + 8] != b"\x00"*4:
        raise SystemExit("CAN 0x4C8 initial B4..B7 is not zero")


def render() -> str:
    import io
    out = io.StringIO(newline="")
    w = csv.DictWriter(out, fieldnames=FIELDNAMES, lineterminator="\n")
    w.writeheader(); w.writerows(ROWS)
    return out.getvalue()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    cf = CF_PATH.read_bytes(); validate(cf)
    text = render()
    if args.check:
        if not args.output.is_file() or args.output.read_text() != text:
            raise SystemExit(f"stale generated artifact: {args.output}")
        print(f"{args.output} is current")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    print(f"Wrote {args.output} rows={len(ROWS)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
